#pragma checksum "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "3FB1C5BF8C6DFD6FCDE1326A1721A478"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9066
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 285 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 280 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 282 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 278 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 277 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 208 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 289 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 208 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 286 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 276 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 275 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 284 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 281 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 283 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 279 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class student_mynum_aspx : global::Student_mynum, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        
        #line 62 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                       
    protected string pubUserName = "";
    protected string pubUserInitial = "";
    protected string pubUserClass = "";
    protected bool pubLoggedIn = false;
    protected string pubSiteTitle = "LearnSite";
    protected string pubLogoUrl = "";

    // Footer settings from ~/App_Data/footersetting.xml
    protected string footerCopyright = "";
    protected string footerIcp = "";
    protected string footerIcpUrl = "";
    protected string footerCustomHtml = "";
    protected bool footerShowPoweredBy = true;
    protected string footerBgColor = "#1e293b";
    protected string footerTextColor = "#94a3b8";
    protected bool footerHasSettings = false;

    private void LoadFooterSettings() {
        try {
            string xmlPath = Server.MapPath("~/App_Data/footersetting.xml");
            if (!System.IO.File.Exists(xmlPath)) return;
            System.Xml.XmlDocument doc = new System.Xml.XmlDocument();
            doc.Load(xmlPath);
            footerCopyright = ReadFooterNode(doc, "copyright");
            footerIcp = ReadFooterNode(doc, "icp");
            footerIcpUrl = ReadFooterNode(doc, "icpUrl");
            footerCustomHtml = ReadFooterNode(doc, "customHtml");
            string pb = ReadFooterNode(doc, "showPoweredBy");
            footerShowPoweredBy = (pb != "false");
            string bg = ReadFooterNode(doc, "bgColor");
            if (!string.IsNullOrEmpty(bg)) footerBgColor = bg;
            string tc = ReadFooterNode(doc, "textColor");
            if (!string.IsNullOrEmpty(tc)) footerTextColor = tc;
            footerHasSettings = true;
        } catch { }
    }

    private string ReadFooterNode(System.Xml.XmlDocument doc, string name) {
        System.Xml.XmlNode node = doc.SelectSingleNode("//" + name);
        if (node != null) return node.InnerText;
        return "";
    }

    protected string GetSiteTitle() {
        try {
            string xmlPath = Server.MapPath("~/website.xml");
            System.Xml.XmlDocument doc = new System.Xml.XmlDocument();
            doc.Load(xmlPath);
            System.Xml.XmlNode node = doc.SelectSingleNode("//add[@key='SiteTitle']");
            if (node != null && node.Attributes["value"] != null)
                return node.Attributes["value"].Value;
        } catch { }
        return "LearnSite";
    }

    protected string GetSiteLogoUrl() {
        string[] exts = { ".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp" };
        foreach (string ext in exts) {
            string path = Server.MapPath("~/images/site-logo" + ext);
            if (System.IO.File.Exists(path))
                return ResolveUrl("~/images/site-logo" + ext) + "?v=" + System.IO.File.GetLastWriteTime(path).Ticks;
        }
        return "";
    }

    protected override void OnPreRender(EventArgs e) {
        pubSiteTitle = GetSiteTitle();
        pubLogoUrl = GetSiteLogoUrl();
        LoadFooterSettings();
        base.OnPreRender(e);
        try {
            HttpCookie sc = Request.Cookies[LearnSite.Common.CookieHelp.stuCookieNname];
            if (sc != null && !string.IsNullOrEmpty(sc.Value)) {
                string cv = sc.Value;
                if (cv.Contains("%")) try { cv = HttpUtility.UrlDecode(cv, System.Text.Encoding.UTF8); } catch {}
                Type ct = typeof(LearnSite.Common.CookieHelp).Assembly.GetType("LearnSite.Model.Cook");
                if (ct != null) {
                    object m = Activator.CreateInstance(ct);
                    System.Reflection.MethodInfo mi = ct.GetMethod("ToModel", System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance);
                    if (mi != null) mi.Invoke(m, new object[]{cv});
                    System.Reflection.PropertyInfo pn = ct.GetProperty("Sname");
                    if (pn != null) { object v = pn.GetValue(m,null); if(v!=null) { string s=v.ToString(); if(s.Contains("%")) try{s=HttpUtility.UrlDecode(s,System.Text.Encoding.UTF8);}catch{} pubUserName=s; if(s.Length>0) pubUserInitial=s.Substring(0,1); pubLoggedIn=true; } }
                    System.Reflection.PropertyInfo pg = ct.GetProperty("Sgrade"); System.Reflection.PropertyInfo pc = ct.GetProperty("Sclass");
                    string g="",c=""; if(pg!=null){object gv=pg.GetValue(m,null);if(gv!=null)g=gv.ToString();} if(pc!=null){object cv2=pc.GetValue(m,null);if(cv2!=null)c=cv2.ToString();}
                    if(!string.IsNullOrEmpty(g)&&g!="0"&&!string.IsNullOrEmpty(c)&&c!="0") pubUserClass=g+"\u5E74\u7EA7"+c+"\u73ED"; else if(!string.IsNullOrEmpty(c)&&c!="0") pubUserClass=c+"\u73ED";
                }
            }
        } catch {}
    }

        #line default
        #line hidden
        
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public student_mynum_aspx() {
            string[] dependencies;
            ((global::Student_mynum)(this)).AppRelativeVirtualPath = "~/student/mynum.aspx";
            if ((global::ASP.student_mynum_aspx.@__initialized == false)) {
                global::ASP.student_mynum_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[1];
                dependencies[0] = "~/student/mynum.aspx";
                global::ASP.student_mynum_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.student_mynum_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control2() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 5 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("学号查询"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Href = "../js/tooltip.css";
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 7 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Href = "../js/pub-header.css";
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 8 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 8 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Href = "../js/pub-footer.css?v=final";
            
            #line default
            #line hidden
            
            #line 8 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 8 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControlHead1() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 4 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            this.Head1 = @__ctrl;
            
            #line 4 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ID = "Head1";
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 4 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 4 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl2;
            
            #line 4 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 4 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl3;
            
            #line 4 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl3 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 4 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl4;
            
            #line 4 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl4 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 4 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 4 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(147094, 5633, false));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDDLgrade() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 208 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.DDLgrade = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 208 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ID = "DDLgrade";
            
            #line default
            #line hidden
            
            #line 208 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(70, System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 208 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.AutoPostBack = true;
            
            #line default
            #line hidden
            
            #line 208 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.DDLgrade_SelectedIndexChanged);
            
            #line default
            #line hidden
            
            #line 208 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.DDLgrade_SelectedIndexChanged);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDDLclass() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 213 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.DDLclass = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 213 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ID = "DDLclass";
            
            #line default
            #line hidden
            
            #line 213 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(70, System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 213 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.AutoPostBack = true;
            
            #line default
            #line hidden
            
            #line 213 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.DDLclass_SelectedIndexChanged);
            
            #line default
            #line hidden
            
            #line 213 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.DDLclass_SelectedIndexChanged);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnSearch() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 216 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.BtnSearch = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 216 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ID = "BtnSearch";
            
            #line default
            #line hidden
            
            #line 216 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Text = "查询";
            
            #line default
            #line hidden
            
            #line 216 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.CssClass = "mn-search-btn";
            
            #line default
            #line hidden
            
            #line 216 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Click -= new System.EventHandler(this.BtnSearch_Click);
            
            #line default
            #line hidden
            
            #line 216 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Click += new System.EventHandler(this.BtnSearch_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTextBoxPwd() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 219 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TextBoxPwd = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 219 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ID = "TextBoxPwd";
            
            #line default
            #line hidden
            
            #line 219 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 219 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(60, System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 219 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
            
            #line default
            #line hidden
            
            #line 219 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onClick", "copy()");
            
            #line default
            #line hidden
            
            #line 219 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 219 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Font.Size = System.Web.UI.WebControls.FontUnit.XLarge;
            
            #line default
            #line hidden
            
            #line 219 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(220, 38, 38)));
            
            #line default
            #line hidden
            
            #line 219 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Text = "123";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Image @__BuildControl__control7() {
            global::System.Web.UI.WebControls.Image @__ctrl;
            
            #line 231 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Image();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 231 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ID = "ImageStu";
            
            #line default
            #line hidden
            
            #line 231 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "stuimg");
            
            #line default
            #line hidden
            
            #line 231 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Visible = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__control8() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 232 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 232 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ID = "HLSnum";
            
            #line default
            #line hidden
            
            #line 232 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.CssClass = "stulink";
            
            #line default
            #line hidden
            
            #line 232 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control8);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBinding__control8(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.HyperLink dataBindingExpressionBuilderTarget;
            System.Web.UI.WebControls.DataListItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.HyperLink)(sender));
            Container = ((System.Web.UI.WebControls.DataListItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line 232 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            dataBindingExpressionBuilderTarget.Text = System.Convert.ToString( Eval("Sname") , System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 232 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            dataBindingExpressionBuilderTarget.ToolTip = System.Convert.ToString( Eval("Snum") , System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control6(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    <div class=\"stunum\">\r\n                        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Image @__ctrl1;
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl1 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<br />\r\n                        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl2;
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl2 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </div>\r\n                "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DataList @__BuildControlDataListsnum() {
            global::System.Web.UI.WebControls.DataList @__ctrl;
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DataList();
            
            #line default
            #line hidden
            this.DataListsnum = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control6));
            
            #line default
            #line hidden
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ID = "DataListsnum";
            
            #line default
            #line hidden
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.RepeatDirection = System.Web.UI.WebControls.RepeatDirection.Horizontal;
            
            #line default
            #line hidden
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.RepeatColumns = 8;
            
            #line default
            #line hidden
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.CellPadding = 4;
            
            #line default
            #line hidden
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.CellSpacing = 4;
            
            #line default
            #line hidden
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ItemDataBound -= new System.Web.UI.WebControls.DataListItemEventHandler(this.DataListsnum_ItemDataBound);
            
            #line default
            #line hidden
            
            #line 226 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ItemDataBound += new System.Web.UI.WebControls.DataListItemEventHandler(this.DataListsnum_ItemDataBound);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 154 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 154 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            
            #line 154 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl1 = this.@__BuildControlDDLgrade();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 154 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            
            #line 154 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl2 = this.@__BuildControlDDLclass();
            
            #line default
            #line hidden
            
            #line 154 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl3;
            
            #line 154 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl3 = this.@__BuildControlBtnSearch();
            
            #line default
            #line hidden
            
            #line 154 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 154 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl4 = this.@__BuildControlTextBoxPwd();
            
            #line default
            #line hidden
            
            #line 154 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DataList @__ctrl5;
            
            #line 154 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl5 = this.@__BuildControlDataListsnum();
            
            #line default
            #line hidden
            
            #line 154 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Renderform1));
            return @__ctrl;
        }
        
        private void @__Renderform1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n    <!-- 顶栏 -->\r\n    <div class=\"pub-hdr\">\r\n        <a href=\"../index.aspx\" cla" +
                    "ss=\"pub-hdr-logo\">\r\n            ");
            
            #line 158 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
               if (!string.IsNullOrEmpty(pubLogoUrl)) { 
            
            #line default
            #line hidden
            @__w.Write("\r\n            <img src=\"");
            
            #line 159 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
              @__w.Write( pubLogoUrl );

            
            #line default
            #line hidden
            @__w.Write("\" alt=\"Logo\" />\r\n            ");
            
            #line 160 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
               } else { 
            
            #line default
            #line hidden
            @__w.Write("\r\n            <span class=\"pub-hdr-logo-fb\">L</span>\r\n            ");
            
            #line 162 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
               } 
            
            #line default
            #line hidden
            @__w.Write("\r\n            <span>");
            
            #line 163 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
          @__w.Write( Server.HtmlEncode(pubSiteTitle) );

            
            #line default
            #line hidden
            @__w.Write("</span>\r\n        </a>\r\n        <div class=\"pub-hdr-space\"></div>\r\n        <div cl" +
                    "ass=\"pub-hdr-actions\">\r\n            ");
            
            #line 167 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
               if (pubLoggedIn) { 
            
            #line default
            #line hidden
            @__w.Write("\r\n            <div class=\"pub-user\">\r\n                <div class=\"pub-user-avatar" +
                    "\">");
            
            #line 169 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                                     @__w.Write( Server.HtmlEncode(pubUserInitial) );

            
            #line default
            #line hidden
            @__w.Write("</div>\r\n                <span class=\"pub-user-name\">");
            
            #line 170 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                                    @__w.Write( Server.HtmlEncode(pubUserName) );

            
            #line default
            #line hidden
            @__w.Write("</span>\r\n                ");
            
            #line 171 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                   if (!string.IsNullOrEmpty(pubUserClass)) { 
            
            #line default
            #line hidden
            @__w.Write("<span class=\"pub-user-class\">");
            
            #line 171 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                                                                                     @__w.Write( Server.HtmlEncode(pubUserClass) );

            
            #line default
            #line hidden
            @__w.Write("</span>");
            
            #line 171 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                                                                                                                                             } 
            
            #line default
            #line hidden
            @__w.Write("\r\n            </div>\r\n            ");
            
            #line 173 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
               } else { 
            
            #line default
            #line hidden
            @__w.Write("\r\n            <a href=\"/index.aspx\" class=\"pub-btn-login\">登录</a>\r\n            <a " +
                    "href=\"../student/register.aspx\" class=\"pub-btn-reg\">注册</a>\r\n            ");
            
            #line 176 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
               } 
            
            #line default
            #line hidden
            this.WriteUTF8ResourceString(@__w, 152727, 2108, false);
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                </div>\r\n                <div class=\"mn-field\">\r\n               " +
                    "     <label>班级</label>\r\n                    ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n                </div>\r\n                ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n                <div class=\"mn-pwd-box\">\r\n                    <span class=\"mn-p" +
                    "wd-label\">密码</span>\r\n                    ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=" +
                    "\"mn-grid-card\">\r\n            ");
            parameterContainer.Controls[4].RenderControl(@__w);
            this.WriteUTF8ResourceString(@__w, 154835, 429, false);
            
            #line 248 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                           if (!string.IsNullOrEmpty(pubLogoUrl)) { 
            
            #line default
            #line hidden
            @__w.Write("\r\n                        <span class=\"site-footer-logo-icon\"><img src=\"");
            
            #line 249 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                                                              @__w.Write( pubLogoUrl );

            
            #line default
            #line hidden
            @__w.Write("\" alt=\"Logo\" /></span>\r\n                        ");
            
            #line 250 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                           } else { 
            
            #line default
            #line hidden
            @__w.Write("\r\n                        <span class=\"site-footer-logo-icon\">L</span>\r\n         " +
                    "               ");
            
            #line 252 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                           } 
            
            #line default
            #line hidden
            @__w.Write("\r\n                        <span>");
            
            #line 253 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                      @__w.Write( Server.HtmlEncode(pubSiteTitle) );

            
            #line default
            #line hidden
            this.WriteUTF8ResourceString(@__w, 155264, 5464, false);
            
            #line 338 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                       if (!string.IsNullOrEmpty(footerCopyright)) { 
            
            #line default
            #line hidden
            @__w.Write("\r\n                    <span class=\"site-footer-copyright\">");
            
            #line 339 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                                                @__w.Write( Server.HtmlEncode(footerCopyright) );

            
            #line default
            #line hidden
            @__w.Write("</span>\r\n                    ");
            
            #line 340 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                       } else { 
            
            #line default
            #line hidden
            @__w.Write("\r\n                    <span class=\"site-footer-copyright\">© {year} LearnSite. All" +
                    " rights reserved</span>\r\n                    ");
            
            #line 342 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                       } 
            
            #line default
            #line hidden
            
            #line 343 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                       if (!string.IsNullOrEmpty(footerIcp)) { 
            
            #line default
            #line hidden
            @__w.Write("\r\n                    <span class=\"site-footer-icp\">\r\n                        ");
            
            #line 345 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                           if (!string.IsNullOrEmpty(footerIcpUrl)) { 
            
            #line default
            #line hidden
            @__w.Write("\r\n                        <a href=\"");
            
            #line 346 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                         @__w.Write( Server.HtmlEncode(footerIcpUrl) );

            
            #line default
            #line hidden
            @__w.Write("\" target=\"_blank\" rel=\"noopener\">");
            
            #line 346 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                                                                                                @__w.Write( Server.HtmlEncode(footerIcp) );

            
            #line default
            #line hidden
            @__w.Write("</a>\r\n                        ");
            
            #line 347 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                           } else { 
            
            #line default
            #line hidden
            
            #line 348 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                @__w.Write( Server.HtmlEncode(footerIcp) );

            
            #line default
            #line hidden
            @__w.Write("\r\n                        ");
            
            #line 349 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                           } 
            
            #line default
            #line hidden
            @__w.Write("\r\n                    </span>\r\n                    ");
            
            #line 351 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                       } 
            
            #line default
            #line hidden
            @__w.Write("\r\n                </div>\r\n                <div class=\"site-footer-bottom-right\">\r" +
                    "\n                    ");
            
            #line 354 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                       if (footerShowPoweredBy) { 
            
            #line default
            #line hidden
            @__w.Write("\r\n                    <span class=\"site-footer-powered\"><a href=\"https://github.c" +
                    "om/learnsite\" target=\"_blank\" rel=\"noopener\">LearnSite</a></span>\r\n             " +
                    "       ");
            
            #line 356 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
                       } 
            
            #line default
            #line hidden
            this.WriteUTF8ResourceString(@__w, 160728, 773, false);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(student_mynum_aspx @__ctrl) {
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl1;
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl1 = this.@__BuildControlHead1();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<body>\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__ctrl2 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\student\mynum.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            this.StyleSheetTheme = "Student";
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.student_mynum_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.student_mynum_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1249213839;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
