#pragma checksum "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "66E7FB788C3507EC4231750F8ABE5117"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9066
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 284 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 281 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 283 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 279 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 285 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 276 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 278 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 275 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 1 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 282 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 286 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 277 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 280 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 289 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class teacher_pixeledit_aspx : global::Teacher_pixeledit, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public teacher_pixeledit_aspx() {
            string[] dependencies;
            ((global::Teacher_pixeledit)(this)).AppRelativeVirtualPath = "~/teacher/pixeledit.aspx";
            if ((global::ASP.teacher_pixeledit_aspx.@__initialized == false)) {
                global::ASP.teacher_pixeledit_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[2];
                dependencies[0] = "~/teacher/pixeledit.aspx";
                dependencies[1] = "~/teacher/Teach.master";
                global::ASP.teacher_pixeledit_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.teacher_pixeledit_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 8 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 8 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "11";
            
            #line default
            #line hidden
            
            #line 8 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "像素画";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control4() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 9 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 9 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "36";
            
            #line default
            #line hidden
            
            #line 9 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "素材库";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control5() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 10 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 10 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "37";
            
            #line default
            #line hidden
            
            #line 10 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "网站设计";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control6() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 11 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 11 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "17";
            
            #line default
            #line hidden
            
            #line 11 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "二维码";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control7() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 12 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "18";
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "在线文档";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control8() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 13 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 13 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "19";
            
            #line default
            #line hidden
            
            #line 13 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "演示文稿";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control9() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 14 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "20";
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "海报设计";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control10() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 15 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 15 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "21";
            
            #line default
            #line hidden
            
            #line 15 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "风格迁移";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control11() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 16 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "22";
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "图像分类";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control12() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 17 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "23";
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "人脸识别";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control13() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 18 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "24";
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "物联网MQTT";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control14() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 19 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 19 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "25";
            
            #line default
            #line hidden
            
            #line 19 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "手绘画布";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control15() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 20 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 20 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "26";
            
            #line default
            #line hidden
            
            #line 20 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "推箱子地图";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control16() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 21 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "27";
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "人工智能对话";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control17() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 22 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "28";
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "语音合成";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control18() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 23 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "29";
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "文字识别";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control19() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 24 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "30";
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "声音分析";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control20() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 25 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "31";
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "井字棋";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control21() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 26 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "32";
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "手写数字识别";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control22() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 27 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "33";
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "Markdown写作";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control23() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 28 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "34";
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "嵌入本地网页";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control24() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 29 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 29 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "35";
            
            #line default
            #line hidden
            
            #line 29 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "文生图";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control2(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl4 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl5;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl5 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl6;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl6 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl7;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl7 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl8;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl8 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl9;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl9 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl10;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl10 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl11;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl11 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl12;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl12 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl13;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl13 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl14;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl14 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl15;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl15 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl15);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl16;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl16 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl16);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl17;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl17 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl17);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl18;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl18 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl18);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl19;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl19 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl19);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl20;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl20 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl20);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl21;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl21 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl21);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl22;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl22 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl22);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDDLTitle() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.DDLTitle = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.ID = "DDLTitle";
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Font.Size = System.Web.UI.WebControls.FontUnit.Medium;
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Enabled = false;
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.AutoPostBack = true;
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            this.@__BuildControl__control2(@__ctrl.Items);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTexttitle() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 31 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.Texttitle = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "TextBoxNormal";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 31 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.ID = "Texttitle";
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200, System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlCheckPublish() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 33 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.CheckPublish = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 33 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.ID = "CheckPublish";
            
            #line default
            #line hidden
            
            #line 33 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "是否发布";
            
            #line default
            #line hidden
            
            #line 33 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Checked = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control26() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 36 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "led";
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "小灯";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control27() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 37 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "fan";
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "风扇";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control28() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 38 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "pump";
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "水泵";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control29() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 39 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 39 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "temperature";
            
            #line default
            #line hidden
            
            #line 39 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "温度";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control30() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 40 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 40 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "humidity";
            
            #line default
            #line hidden
            
            #line 40 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "湿度";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control31() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 41 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 41 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "sound";
            
            #line default
            #line hidden
            
            #line 41 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "声音";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control32() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 42 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 42 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "light";
            
            #line default
            #line hidden
            
            #line 42 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "亮度";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control33() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 43 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 43 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Value = "distance";
            
            #line default
            #line hidden
            
            #line 43 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "距离";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control25(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl1 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl2 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl3 = this.@__BuildControl__control28();
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl4 = this.@__BuildControl__control29();
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl5;
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl5 = this.@__BuildControl__control30();
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl6;
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl6 = this.@__BuildControl__control31();
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl7;
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl7 = this.@__BuildControl__control32();
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl8;
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl8 = this.@__BuildControl__control33();
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Add(@__ctrl8);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBoxList @__BuildControlCkdevice() {
            global::System.Web.UI.WebControls.CheckBoxList @__ctrl;
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBoxList();
            
            #line default
            #line hidden
            this.Ckdevice = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.ID = "Ckdevice";
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.RepeatLayout = System.Web.UI.WebControls.RepeatLayout.Flow;
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.RepeatDirection = System.Web.UI.WebControls.RepeatDirection.Horizontal;
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Font.Size = System.Web.UI.WebControls.FontUnit.Small;
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            this.@__BuildControl__control25(@__ctrl.Items);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTexturl() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 46 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.Texturl = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "TextBoxNormal";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 46 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.ID = "Texturl";
            
            #line default
            #line hidden
            
            #line 46 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200, System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 46 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 46 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "https://image.baidu.com";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlmcontent() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            
            #line 72 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            
            #line default
            #line hidden
            this.mcontent = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 72 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.ID = "mcontent";
            
            #line default
            #line hidden
            
            #line 72 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "width: 830px; height:450px;");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabelmsg() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 75 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Labelmsg = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 75 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.ID = "Labelmsg";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDDLMgid() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 77 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.DDLMgid = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 77 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.ID = "DDLMgid";
            
            #line default
            #line hidden
            
            #line 77 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Font.Size = new System.Web.UI.WebControls.FontUnit(new System.Web.UI.WebControls.Unit(9, System.Web.UI.WebControls.UnitType.Point));
            
            #line default
            #line hidden
            
            #line 77 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(160, System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 77 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Font.Names = new string[] {
                    "Arial"};
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnedit() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 82 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.Btnedit = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "BtnNormal";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 82 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.ID = "Btnedit";
            
            #line default
            #line hidden
            
            #line 82 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "修改主题";
            
            #line default
            #line hidden
            
            #line 82 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Click -= new System.EventHandler(this.Btnedit_Click);
            
            #line default
            #line hidden
            
            #line 82 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Click += new System.EventHandler(this.Btnedit_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnCourse() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 83 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.BtnCourse = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "BtnNormal";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 83 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.ID = "BtnCourse";
            
            #line default
            #line hidden
            
            #line 83 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Text = "学案返回";
            
            #line default
            #line hidden
            
            #line 83 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Click -= new System.EventHandler(this.BtnCourse_Click);
            
            #line default
            #line hidden
            
            #line 83 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Click += new System.EventHandler(this.BtnCourse_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl1 = this.@__BuildControlDDLTitle();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl2 = this.@__BuildControlTexttitle();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl3;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl3 = this.@__BuildControlCheckPublish();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBoxList @__ctrl4;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl4 = this.@__BuildControlCkdevice();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl5;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl5 = this.@__BuildControlTexturl();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl6;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl6 = this.@__BuildControlmcontent();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl7;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl7 = this.@__BuildControlLabelmsg();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl8;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl8 = this.@__BuildControlDDLMgid();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl9;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl9 = this.@__BuildControlBtnedit();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl10;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl10 = this.@__BuildControlBtnCourse();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderContent1));
        }
        
        private void @__RenderContent1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n<div  class=\"cplace\">\r\n    <div  class=\"cleft\">\r\n        ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n        主题：");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n\r\n        ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write("\r\n\r\n        </div> \r\n        <div  >\r\n        <script charset=\"utf-8\" src=\"../kin" +
                    "deditor/kindeditor-min.js\"></script>\r\n\t\t<script charset=\"utf-8\" src=\"../kindedit" +
                    "or/lang/zh_CN.js\"></script>\r\n\t\t<script>\r\n\t\t    var editor;\r\n            var cid=" +
                    " ");
            
            #line 54 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
             @__w.Write(myCid() );

            
            #line default
            #line hidden
            this.WriteUTF8ResourceString(@__w, 196322, 623, true);
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write(" \r\n    </div>\r\n     <div  class=\"placehold\">\r\n               ");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write("\r\n               <br />\r\n               选择自定义评价标准：");
            parameterContainer.Controls[7].RenderControl(@__w);
            @__w.Write("\r\n               <br />\r\n         <br />\r\n              ");
            parameterContainer.Controls[8].RenderControl(@__w);
            @__w.Write("&nbsp;&nbsp;&nbsp;\r\n              ");
            parameterContainer.Controls[9].RenderControl(@__w);
            @__w.Write("<br />\r\n         <br />\r\n         </div>\r\n           \r\n        </div>\r\n");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(teacher_pixeledit_aspx @__ctrl) {
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__ctrl.MasterPageFile = "~/teacher/Teach.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            this.AddContentTemplate("Content", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite\teacher\pixeledit.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            this.StyleSheetTheme = "Teacher";
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.teacher_pixeledit_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.teacher_pixeledit_aspx.@__fileDependencies);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 2030155842;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
