//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9066
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "2.0.50727.9062")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_8fzq_xfe {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_8fzq_xfe() {
        }
        
        static object Create_ASP_teacher_sitelog_aspx() {
            return new ASP.teacher_sitelog_aspx();
        }
        
        static object Create_ASP_teacher_shareview_aspx() {
            return new ASP.teacher_shareview_aspx();
        }
        
        static object Create_ASP_teacher_teach_master() {
            return new ASP.teacher_teach_master();
        }
        
        static object Create_ASP_teacher_studentedit_aspx() {
            return new ASP.teacher_studentedit_aspx();
        }
        
        static object Create_ASP_teacher_studentworks_aspx() {
            return new ASP.teacher_studentworks_aspx();
        }
        
        static object Create_ASP_teacher_softnomic_aspx() {
            return new ASP.teacher_softnomic_aspx();
        }
        
        static object Create_ASP_teacher_circlegroups_aspx() {
            return new ASP.teacher_circlegroups_aspx();
        }
        
        static object Create_ASP_teacher_workshow_aspx() {
            return new ASP.teacher_workshow_aspx();
        }
    }
}
