#pragma checksum "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "018F110C494BD35318882D8F67BE9BC9"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9066
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 284 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 281 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 283 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 279 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 285 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 276 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 278 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 275 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 1 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 282 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 286 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 277 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 280 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 289 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class teacher_programshow_aspx : global::Teacher_programshow, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public teacher_programshow_aspx() {
            string[] dependencies;
            ((global::Teacher_programshow)(this)).AppRelativeVirtualPath = "~/teacher/programshow.aspx";
            if ((global::ASP.teacher_programshow_aspx.@__initialized == false)) {
                global::ASP.teacher_programshow_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[2];
                dependencies[0] = "~/teacher/programshow.aspx";
                dependencies[1] = "~/teacher/Teach.master";
                global::ASP.teacher_programshow_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.teacher_programshow_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabelMtitle() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 7 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.LabelMtitle = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 7 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ID = "LabelMtitle";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabelMdate() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 10 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.LabelMdate = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 10 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ID = "LabelMdate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Image @__BuildControlImageType() {
            global::System.Web.UI.WebControls.Image @__ctrl;
            
            #line 11 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Image();
            
            #line default
            #line hidden
            this.ImageType = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 11 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ID = "ImageType";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabelMfiletype() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 12 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.LabelMfiletype = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 12 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ID = "LabelMfiletype";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControlHlexample() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 13 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            this.Hlexample = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 13 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ID = "Hlexample";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlCheckPublish() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 14 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.CheckPublish = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 14 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ID = "CheckPublish";
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.Text = "是否发布";
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.Enabled = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlCheckMicoWorld() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 16 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.CheckMicoWorld = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 16 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ID = "CheckMicoWorld";
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.Text = "作品继承";
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ToolTip = "加载上一节的编程作品，适合项目学习";
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.Enabled = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControlHLMgid() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 19 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            this.HLMgid = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 19 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ID = "HLMgid";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 19 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("评价标准"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControlBtnEdit() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            
            #line 21 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            
            #line default
            #line hidden
            this.BtnEdit = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 21 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ID = "BtnEdit";
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ToolTip = "点击修改";
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ImageUrl = "~/images/edit.gif";
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "width: 16px");
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.Click -= new System.Web.UI.ImageClickEventHandler(this.BtnEdit_Click);
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.Click += new System.Web.UI.ImageClickEventHandler(this.BtnEdit_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControlBtnReturnSmall() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            
            #line 24 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            
            #line default
            #line hidden
            this.BtnReturnSmall = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 24 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ID = "BtnReturnSmall";
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ToolTip = "返回";
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ImageUrl = "~/images/return.gif";
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "width: 16px");
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.Click -= new System.Web.UI.ImageClickEventHandler(this.BtnReturnSmall_Click);
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.Click += new System.Web.UI.ImageClickEventHandler(this.BtnReturnSmall_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlMcontent() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 28 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            
            #line default
            #line hidden
            this.Mcontent = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 28 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ID = "Mcontent";
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "coursecontent");
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 28 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\t\r\n\t\t"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControlLinkBtn() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            
            #line 31 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            
            #line default
            #line hidden
            this.LinkBtn = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "LinkBtn";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 31 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.ID = "LinkBtn";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 31 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("返回学案"));
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.Click -= new System.EventHandler(this.LinkBtn_Click);
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.Click += new System.EventHandler(this.LinkBtn_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<div class=\"courseshow\">\r\n    <br />\r\n        <div   class=\"missiontitle\">\r\n   " +
                        " "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl1 = this.@__BuildControlLabelMtitle();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n   </div><br />\r\n    <div class=\"courseother\">\r\n       日期："));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl2;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl2 = this.@__BuildControlLabelMdate();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t&nbsp;作品类型："));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Image @__ctrl3;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl3 = this.@__BuildControlImageType();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl4;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl4 = this.@__BuildControlLabelMfiletype();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            &nbsp;实例:"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl5;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl5 = this.@__BuildControlHlexample();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl6;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl6 = this.@__BuildControlCheckPublish();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("&nbsp;\r\n            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl7;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl7 = this.@__BuildControlCheckMicoWorld();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            &nbsp;"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl8;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl8 = this.@__BuildControlHLMgid();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ImageButton @__ctrl9;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl9 = this.@__BuildControlBtnEdit();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n   &nbsp;"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ImageButton @__ctrl10;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl10 = this.@__BuildControlBtnReturnSmall();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n   </div>\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl11;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl11 = this.@__BuildControlMcontent();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t<br />\r\n         "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.LinkButton @__ctrl12;
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl12 = this.@__BuildControlLinkBtn();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <br />\r\n\t\t<br />\r\n\r\n</div> \r\n    <br />\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(teacher_programshow_aspx @__ctrl) {
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__ctrl.MasterPageFile = "~/teacher/Teach.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            this.AddContentTemplate("Content", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Users\Administrator\Downloads\LearnSite2026-1-5\LearnSite2\teacher\programshow.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            this.StyleSheetTheme = "Teacher";
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.teacher_programshow_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.teacher_programshow_aspx.@__fileDependencies);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -971592533;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
