//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9066
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "2.0.50727.9062")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_qpdcwzwc {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_qpdcwzwc() {
        }
        
        static object Create_ASP_student_excellentwork_aspx() {
            return new ASP.student_excellentwork_aspx();
        }
        
        static object Create_ASP_student_pythonshow_aspx() {
            return new ASP.student_pythonshow_aspx();
        }
        
        static object Create_ASP_student_quizview_aspx() {
            return new ASP.student_quizview_aspx();
        }
        
        static object Create_ASP_student_programshow_aspx() {
            return new ASP.student_programshow_aspx();
        }
        
        static object Create_ASP_student_htmleditor_aspx() {
            return new ASP.student_htmleditor_aspx();
        }
        
        static object Create_ASP_student_quizrank_aspx() {
            return new ASP.student_quizrank_aspx();
        }
        
        static object Create_ASP_student_test_autonomic_data_aspx() {
            return new ASP.student_test_autonomic_data_aspx();
        }
        
        static object Create_ASP_student_style_aspx() {
            return new ASP.student_style_aspx();
        }
        
        static object Create_ASP_student_softwaredownload_aspx() {
            return new ASP.student_softwaredownload_aspx();
        }
        
        static object Create_ASP_student_gamelist_aspx() {
            return new ASP.student_gamelist_aspx();
        }
        
        static object Create_ASP_student_codeshare_aspx() {
            return new ASP.student_codeshare_aspx();
        }
        
        static object Create_ASP_student_downfile_fixed_aspx() {
            return new ASP.student_downfile_fixed_aspx();
        }
        
        static object Create_ASP_student_roomselect_aspx() {
            return new ASP.student_roomselect_aspx();
        }
        
        static object Create_ASP_student_webstoresql_aspx() {
            return new ASP.student_webstoresql_aspx();
        }
        
        static object Create_ASP_student_mysurveyrank_aspx() {
            return new ASP.student_mysurveyrank_aspx();
        }
        
        static object Create_ASP_student_masterwork_aspx() {
            return new ASP.student_masterwork_aspx();
        }
        
        static object Create_ASP_student_pptist_aspx() {
            return new ASP.student_pptist_aspx();
        }
        
        static object Create_ASP_student_topicdiscuss_backup_aspx() {
            return new ASP.student_topicdiscuss_backup_aspx();
        }
        
        static object Create_ASP_student_downwork_aspx() {
            return new ASP.student_downwork_aspx();
        }
        
        static object Create_ASP_student_iframe_aspx() {
            return new ASP.student_iframe_aspx();
        }
        
        static object Create_ASP_student_mpptx_aspx() {
            return new ASP.student_mpptx_aspx();
        }
        
        static object Create_ASP_student_htmledit_aspx() {
            return new ASP.student_htmledit_aspx();
        }
        
        static object Create_ASP_student_autonomiccategory_aspx() {
            return new ASP.student_autonomiccategory_aspx();
        }
    }
}
