#pragma checksum "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "003253D135E95BA2856B3D4B01E6A528"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9066
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 284 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 281 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 283 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 279 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 285 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 276 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 278 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 275 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 1 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 282 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 286 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 277 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 280 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 289 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class teacher_softwaredownloadadd_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        
        #line 358 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtName;
        
        #line default
        #line hidden
        
        
        #line 362 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtVersion;
        
        #line default
        #line hidden
        
        
        #line 367 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtDesc;
        
        #line default
        #line hidden
        
        
        #line 378 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtIcon;
        
        #line default
        #line hidden
        
        
        #line 383 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.FileUpload FileUploadIcon;
        
        #line default
        #line hidden
        
        
        #line 414 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtDownloadUrl;
        
        #line default
        #line hidden
        
        
        #line 419 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.FileUpload FileUploadSoftware;
        
        #line default
        #line hidden
        
        
        #line 427 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtDownloadUrlWin;
        
        #line default
        #line hidden
        
        
        #line 432 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.FileUpload FileUploadWin;
        
        #line default
        #line hidden
        
        
        #line 439 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtDownloadUrlMac;
        
        #line default
        #line hidden
        
        
        #line 444 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.FileUpload FileUploadMac;
        
        #line default
        #line hidden
        
        
        #line 451 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtDownloadUrlLinux;
        
        #line default
        #line hidden
        
        
        #line 456 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.FileUpload FileUploadLinux;
        
        #line default
        #line hidden
        
        
        #line 463 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.Button BtnAdd;
        
        #line default
        #line hidden
        
        
        #line 464 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
        protected global::System.Web.UI.WebControls.HyperLink HlkCancel;
        
        #line default
        #line hidden
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        
        #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
                       
    protected int myHid = 0;
    protected string pageMsg = "";

    private string GetConnStr()
    {
        string cs = null;
        try
        {
            Type dbType = typeof(LearnSite.Common.CookieHelp).Assembly.GetType("LearnSite.DBUtility.DbHelperSQL");
            if (dbType != null)
            {
                System.Reflection.FieldInfo f = dbType.GetField("connectionString",
                    System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
                if (f != null) cs = f.GetValue(null) as string;
            }
        }
        catch { }
        if (string.IsNullOrEmpty(cs))
        { try { cs = System.Configuration.ConfigurationManager.ConnectionStrings["SqlServer"].ConnectionString; } catch { } }
        if (cs != null && cs.ToLower().IndexOf("connection timeout") < 0 && cs.ToLower().IndexOf("connect timeout") < 0)
            cs = cs.TrimEnd(';') + ";Connection Timeout=5;";
        return cs;
    }

    private void LoadTeacher()
    {
        try
        {
            HttpCookie tc = Request.Cookies[LearnSite.Common.CookieHelp.teaCookieNname];
            if (tc != null && !string.IsNullOrEmpty(tc.Value))
            {
                Type ct = typeof(LearnSite.Common.CookieHelp).Assembly.GetType("LearnSite.Model.TeaCook");
                if (ct != null)
                {
                    object m = Activator.CreateInstance(ct);
                    System.Reflection.MethodInfo mi = ct.GetMethod("ToModel",
                        System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Static);
                    if (mi != null) mi.Invoke(m, new object[] { tc.Value });
                    System.Reflection.PropertyInfo p = ct.GetProperty("Hid");
                    if (p != null) { object v = p.GetValue(m, null); if (v != null) int.TryParse(v.ToString(), out myHid); }
                }
            }
        }
        catch { }
    }

    protected void Page_Load(object sender, EventArgs e)
    {
        LoadTeacher();
        if (!IsPostBack)
        {
            EnsureTableStructure();
        }
    }

    private void EnsureTableStructure()
    {
        string cs = GetConnStr(); if (string.IsNullOrEmpty(cs)) return;
        try
        {
            using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(cs))
            {
                conn.Open();
                
                // 检查表是否存在
                string checkTable = @"
                    IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SoftwareDownload]') AND type in (N'U'))
                    BEGIN
                        CREATE TABLE [dbo].[SoftwareDownload](
                            [Sid] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
                            [Sname] [nvarchar](200) NOT NULL,
                            [Sversion] [nvarchar](50) NULL,
                            [Sicon] [nvarchar](500) NULL,
                            [Sdesc] [nvarchar](2000) NULL,
                            [Sdownloadurl] [nvarchar](500) NULL,
                            [Sfilename] [nvarchar](200) NULL,
                            [Sfilesize] [bigint] NULL,
                            [Sdownloads] [int] NULL DEFAULT 0,
                            [Sactive] [bit] NULL DEFAULT 1,
                            [Shid] [int] NULL,
                            [Sdate] [datetime] NULL DEFAULT GETDATE(),
                            [SdownloadurlWin] [nvarchar](500) NULL,
                            [SdownloadurlMac] [nvarchar](500) NULL,
                            [SdownloadurlLinux] [nvarchar](500) NULL,
                            [SfilenameWin] [nvarchar](200) NULL,
                            [SfilenameMac] [nvarchar](200) NULL,
                            [SfilenameLinux] [nvarchar](200) NULL,
                            [SfilesizeWin] [bigint] NULL,
                            [SfilesizeMac] [bigint] NULL,
                            [SfilesizeLinux] [bigint] NULL
                        )
                    END";
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(checkTable, conn))
                {
                    cmd.ExecuteNonQuery();
                }
                
                // 检查并添加缺失的列
                string addColumns = @"
                    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[SoftwareDownload]') AND name = 'SdownloadurlWin')
                    BEGIN
                        ALTER TABLE [dbo].[SoftwareDownload] ADD 
                            [SdownloadurlWin] [nvarchar](500) NULL,
                            [SdownloadurlMac] [nvarchar](500) NULL,
                            [SdownloadurlLinux] [nvarchar](500) NULL,
                            [SfilenameWin] [nvarchar](200) NULL,
                            [SfilenameMac] [nvarchar](200) NULL,
                            [SfilenameLinux] [nvarchar](200) NULL,
                            [SfilesizeWin] [bigint] NULL,
                            [SfilesizeMac] [bigint] NULL,
                            [SfilesizeLinux] [bigint] NULL
                    END";
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(addColumns, conn))
                {
                    cmd.ExecuteNonQuery();
                }
            }
        }
        catch (Exception ex) { pageMsg = "数据库初始化失败: " + ex.Message; }
    }

    protected void BtnAdd_Click(object sender, EventArgs e)
    {
        string name = TxtName.Text.Trim();
        if (string.IsNullOrEmpty(name)) { pageMsg = "请输入软件名称"; return; }
        string iconPath = TxtIcon.Text.Trim();
        string downloadUrl = TxtDownloadUrl.Text.Trim();
        string fileName = "";
        long fileSize = 0;
        string downloadUrlWin = TxtDownloadUrlWin.Text.Trim();
        string fileNameWin = "";
        long fileSizeWin = 0;
        string downloadUrlMac = TxtDownloadUrlMac.Text.Trim();
        string fileNameMac = "";
        long fileSizeMac = 0;
        string downloadUrlLinux = TxtDownloadUrlLinux.Text.Trim();
        string fileNameLinux = "";
        long fileSizeLinux = 0;

        // 处理图标上传
        if (FileUploadIcon.HasFile)
        {
            try
            {
                string iconFileName = FileUploadIcon.FileName;
                string iconFileExt = System.IO.Path.GetExtension(iconFileName).ToLower();
                if (iconFileExt != ".jpg" && iconFileExt != ".jpeg" && iconFileExt != ".png" && iconFileExt != ".gif")
                { pageMsg = "图标只支持 JPG、PNG、GIF 格式"; return; }
                if (FileUploadIcon.PostedFile.ContentLength > 2 * 1024 * 1024)
                { pageMsg = "图标大小不能超过 2MB"; return; }
                string newIconName = DateTime.Now.ToString("yyyyMMddHHmmss") + "_" + Guid.NewGuid().ToString("N").Substring(0, 8) + iconFileExt;
                string uploadFolder = Server.MapPath("~/images/software/");
                if (!System.IO.Directory.Exists(uploadFolder)) System.IO.Directory.CreateDirectory(uploadFolder);
                string iconFilePath = System.IO.Path.Combine(uploadFolder, newIconName);
                FileUploadIcon.SaveAs(iconFilePath);
                iconPath = "~/images/software/" + newIconName;
            }
            catch (Exception ex) { pageMsg = "图标上传失败: " + ex.Message; return; }
        }

        // 处理通用软件文件上传
        if (FileUploadSoftware.HasFile)
        {
            try
            {
                fileName = FileUploadSoftware.FileName;
                fileSize = FileUploadSoftware.PostedFile.ContentLength;
                if (fileSize > 500 * 1024 * 1024) { pageMsg = "软件文件大小不能超过 500MB"; return; }
                string fileExt = System.IO.Path.GetExtension(fileName).ToLower();
                string newFileName = DateTime.Now.ToString("yyyyMMddHHmmss") + "_" + Guid.NewGuid().ToString("N").Substring(0, 8) + fileExt;
                string uploadFolder = Server.MapPath("~/downloads/software/");
                if (!System.IO.Directory.Exists(uploadFolder)) System.IO.Directory.CreateDirectory(uploadFolder);
                string filePath = System.IO.Path.Combine(uploadFolder, newFileName);
                FileUploadSoftware.SaveAs(filePath);
                downloadUrl = "~/downloads/software/" + newFileName;
            }
            catch (Exception ex) { pageMsg = "软件文件上传失败: " + ex.Message; return; }
        }

        // 处理Windows版本文件上传
        if (FileUploadWin.HasFile)
        {
            try
            {
                fileNameWin = FileUploadWin.FileName;
                fileSizeWin = FileUploadWin.PostedFile.ContentLength;
                if (fileSizeWin > 500 * 1024 * 1024) { pageMsg = "Windows版本文件大小不能超过 500MB"; return; }
                string fileExt = System.IO.Path.GetExtension(fileNameWin).ToLower();
                string newFileName = "win_" + DateTime.Now.ToString("yyyyMMddHHmmss") + "_" + Guid.NewGuid().ToString("N").Substring(0, 8) + fileExt;
                string uploadFolder = Server.MapPath("~/downloads/software/");
                if (!System.IO.Directory.Exists(uploadFolder)) System.IO.Directory.CreateDirectory(uploadFolder);
                string filePath = System.IO.Path.Combine(uploadFolder, newFileName);
                FileUploadWin.SaveAs(filePath);
                downloadUrlWin = "~/downloads/software/" + newFileName;
            }
            catch (Exception ex) { pageMsg = "Windows版本上传失败: " + ex.Message; return; }
        }

        // 处理Mac版本文件上传
        if (FileUploadMac.HasFile)
        {
            try
            {
                fileNameMac = FileUploadMac.FileName;
                fileSizeMac = FileUploadMac.PostedFile.ContentLength;
                if (fileSizeMac > 500 * 1024 * 1024) { pageMsg = "Mac版本文件大小不能超过 500MB"; return; }
                string fileExt = System.IO.Path.GetExtension(fileNameMac).ToLower();
                string newFileName = "mac_" + DateTime.Now.ToString("yyyyMMddHHmmss") + "_" + Guid.NewGuid().ToString("N").Substring(0, 8) + fileExt;
                string uploadFolder = Server.MapPath("~/downloads/software/");
                if (!System.IO.Directory.Exists(uploadFolder)) System.IO.Directory.CreateDirectory(uploadFolder);
                string filePath = System.IO.Path.Combine(uploadFolder, newFileName);
                FileUploadMac.SaveAs(filePath);
                downloadUrlMac = "~/downloads/software/" + newFileName;
            }
            catch (Exception ex) { pageMsg = "Mac版本上传失败: " + ex.Message; return; }
        }

        // 处理Linux版本文件上传
        if (FileUploadLinux.HasFile)
        {
            try
            {
                fileNameLinux = FileUploadLinux.FileName;
                fileSizeLinux = FileUploadLinux.PostedFile.ContentLength;
                if (fileSizeLinux > 500 * 1024 * 1024) { pageMsg = "Linux版本文件大小不能超过 500MB"; return; }
                string fileExt = System.IO.Path.GetExtension(fileNameLinux).ToLower();
                string newFileName = "linux_" + DateTime.Now.ToString("yyyyMMddHHmmss") + "_" + Guid.NewGuid().ToString("N").Substring(0, 8) + fileExt;
                string uploadFolder = Server.MapPath("~/downloads/software/");
                if (!System.IO.Directory.Exists(uploadFolder)) System.IO.Directory.CreateDirectory(uploadFolder);
                string filePath = System.IO.Path.Combine(uploadFolder, newFileName);
                FileUploadLinux.SaveAs(filePath);
                downloadUrlLinux = "~/downloads/software/" + newFileName;
            }
            catch (Exception ex) { pageMsg = "Linux版本上传失败: " + ex.Message; return; }
        }

        string cs = GetConnStr(); if (string.IsNullOrEmpty(cs)) return;
        try
        {
            using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(cs))
            {
                conn.Open();
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                    @"INSERT INTO SoftwareDownload(Sname,Sversion,Sicon,Sdesc,Sdownloadurl,Sfilename,Sfilesize,
                      SdownloadurlWin,SdownloadurlMac,SdownloadurlLinux,SfilenameWin,SfilenameMac,SfilenameLinux,
                      SfilesizeWin,SfilesizeMac,SfilesizeLinux,Sdownloads,Shid,Sdate,Sactive) 
                      VALUES(@name,@version,@icon,@desc,@url,@filename,@filesize,
                      @urlWin,@urlMac,@urlLinux,@filenameWin,@filenameMac,@filenameLinux,
                      @filesizeWin,@filesizeMac,@filesizeLinux,0,@hid,GETDATE(),1)", conn))
                {
                    cmd.Parameters.AddWithValue("@name", name);
                    cmd.Parameters.AddWithValue("@version", TxtVersion.Text.Trim());
                    cmd.Parameters.AddWithValue("@icon", iconPath);
                    cmd.Parameters.AddWithValue("@desc", TxtDesc.Text.Trim());
                    cmd.Parameters.AddWithValue("@url", downloadUrl);
                    cmd.Parameters.AddWithValue("@filename", fileName);
                    cmd.Parameters.AddWithValue("@filesize", fileSize);
                    cmd.Parameters.AddWithValue("@urlWin", downloadUrlWin);
                    cmd.Parameters.AddWithValue("@urlMac", downloadUrlMac);
                    cmd.Parameters.AddWithValue("@urlLinux", downloadUrlLinux);
                    cmd.Parameters.AddWithValue("@filenameWin", fileNameWin);
                    cmd.Parameters.AddWithValue("@filenameMac", fileNameMac);
                    cmd.Parameters.AddWithValue("@filenameLinux", fileNameLinux);
                    cmd.Parameters.AddWithValue("@filesizeWin", fileSizeWin);
                    cmd.Parameters.AddWithValue("@filesizeMac", fileSizeMac);
                    cmd.Parameters.AddWithValue("@filesizeLinux", fileSizeLinux);
                    cmd.Parameters.AddWithValue("@hid", myHid);
                    cmd.ExecuteNonQuery();
                }
            }
            Response.Redirect("~/teacher/softwaredownload.aspx");
        }
        catch (Exception ex) { pageMsg = "添加失败: " + ex.Message; }
    }

        #line default
        #line hidden
        
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public teacher_softwaredownloadadd_aspx() {
            string[] dependencies;
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/teacher/softwaredownloadadd.aspx";
            if ((global::ASP.teacher_softwaredownloadadd_aspx.@__initialized == false)) {
                global::ASP.teacher_softwaredownloadadd_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[2];
                dependencies[0] = "~/teacher/softwaredownloadadd.aspx";
                dependencies[1] = "~/teacher/Teach.master";
                global::ASP.teacher_softwaredownloadadd_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.teacher_softwaredownloadadd_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 358 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 358 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "TxtName";
            
            #line default
            #line hidden
            
            #line 358 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.MaxLength = 200;
            
            #line default
            #line hidden
            
            #line 358 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "如：Visual Studio Code");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtVersion() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 362 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtVersion = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 362 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "TxtVersion";
            
            #line default
            #line hidden
            
            #line 362 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            
            #line 362 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "如：1.85.0");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtDesc() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 367 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtDesc = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 367 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "TxtDesc";
            
            #line default
            #line hidden
            
            #line 367 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.MaxLength = 2000;
            
            #line default
            #line hidden
            
            #line 367 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.TextMode = System.Web.UI.WebControls.TextBoxMode.MultiLine;
            
            #line default
            #line hidden
            
            #line 367 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.Rows = 6;
            
            #line default
            #line hidden
            
            #line 367 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "请输入软件的详细介绍...");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtIcon() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 378 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtIcon = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 378 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "TxtIcon";
            
            #line default
            #line hidden
            
            #line 378 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.MaxLength = 500;
            
            #line default
            #line hidden
            
            #line 378 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "如：https://example.com/icon.png");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlFileUploadIcon() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            
            #line 383 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            
            #line default
            #line hidden
            this.FileUploadIcon = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 383 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "FileUploadIcon";
            
            #line default
            #line hidden
            
            #line 383 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.CssClass = "swda-file-upload";
            
            #line default
            #line hidden
            
            #line 383 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("accept", "image/*");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtDownloadUrl() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 414 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtDownloadUrl = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 414 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "TxtDownloadUrl";
            
            #line default
            #line hidden
            
            #line 414 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.MaxLength = 500;
            
            #line default
            #line hidden
            
            #line 414 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "如：https://example.com/software.exe");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlFileUploadSoftware() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            
            #line 419 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            
            #line default
            #line hidden
            this.FileUploadSoftware = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 419 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "FileUploadSoftware";
            
            #line default
            #line hidden
            
            #line 419 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.CssClass = "swda-file-upload";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtDownloadUrlWin() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 427 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtDownloadUrlWin = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 427 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "TxtDownloadUrlWin";
            
            #line default
            #line hidden
            
            #line 427 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.MaxLength = 500;
            
            #line default
            #line hidden
            
            #line 427 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "如：https://example.com/software-win.exe");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlFileUploadWin() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            
            #line 432 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            
            #line default
            #line hidden
            this.FileUploadWin = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 432 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "FileUploadWin";
            
            #line default
            #line hidden
            
            #line 432 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.CssClass = "swda-file-upload";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtDownloadUrlMac() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 439 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtDownloadUrlMac = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 439 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "TxtDownloadUrlMac";
            
            #line default
            #line hidden
            
            #line 439 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.MaxLength = 500;
            
            #line default
            #line hidden
            
            #line 439 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "如：https://example.com/software-mac.dmg");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlFileUploadMac() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            
            #line 444 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            
            #line default
            #line hidden
            this.FileUploadMac = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 444 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "FileUploadMac";
            
            #line default
            #line hidden
            
            #line 444 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.CssClass = "swda-file-upload";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtDownloadUrlLinux() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 451 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtDownloadUrlLinux = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 451 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "TxtDownloadUrlLinux";
            
            #line default
            #line hidden
            
            #line 451 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.MaxLength = 500;
            
            #line default
            #line hidden
            
            #line 451 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "如：https://example.com/software-linux.tar.gz");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlFileUploadLinux() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            
            #line 456 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            
            #line default
            #line hidden
            this.FileUploadLinux = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 456 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "FileUploadLinux";
            
            #line default
            #line hidden
            
            #line 456 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.CssClass = "swda-file-upload";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnAdd() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 463 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.BtnAdd = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 463 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "BtnAdd";
            
            #line default
            #line hidden
            
            #line 463 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.Text = "添加软件";
            
            #line default
            #line hidden
            
            #line 463 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.CssClass = "swda-btn swda-btn-primary";
            
            #line default
            #line hidden
            
            #line 463 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.Click += new System.EventHandler(this.BtnAdd_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControlHlkCancel() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 464 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            this.HlkCancel = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 464 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.ID = "HlkCancel";
            
            #line default
            #line hidden
            
            #line 464 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.NavigateUrl = "~/teacher/softwaredownload.aspx";
            
            #line default
            #line hidden
            
            #line 464 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.CssClass = "swda-btn";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 464 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("取消"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl1 = this.@__BuildControlTxtName();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl2 = this.@__BuildControlTxtVersion();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl3 = this.@__BuildControlTxtDesc();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl4 = this.@__BuildControlTxtIcon();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.FileUpload @__ctrl5;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl5 = this.@__BuildControlFileUploadIcon();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl6 = this.@__BuildControlTxtDownloadUrl();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.FileUpload @__ctrl7;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl7 = this.@__BuildControlFileUploadSoftware();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl8 = this.@__BuildControlTxtDownloadUrlWin();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.FileUpload @__ctrl9;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl9 = this.@__BuildControlFileUploadWin();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl10;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl10 = this.@__BuildControlTxtDownloadUrlMac();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.FileUpload @__ctrl11;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl11 = this.@__BuildControlFileUploadMac();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl12;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl12 = this.@__BuildControlTxtDownloadUrlLinux();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.FileUpload @__ctrl13;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl13 = this.@__BuildControlFileUploadLinux();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl14;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl14 = this.@__BuildControlBtnAdd();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl15;
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl15 = this.@__BuildControlHlkCancel();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderContent1));
        }
        
        private void @__RenderContent1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.WriteUTF8ResourceString(@__w, 265231, 5401, false);
            
            #line 334 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
       if (!string.IsNullOrEmpty(pageMsg)) { 
            
            #line default
            #line hidden
            @__w.Write("\r\n    <div class=\"swda-msg\">");
            
            #line 335 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
                  @__w.Write( Server.HtmlEncode(pageMsg) );

            
            #line default
            #line hidden
            @__w.Write("</div>\r\n    ");
            
            #line 336 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
       } 
            
            #line default
            #line hidden
            this.WriteUTF8ResourceString(@__w, 270632, 1328, false);
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n            <div class=\"swda-form-group\">\r\n                " +
                    "<label>版本号</label>\r\n                ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n                <small>可选，用于标识软件版本</small>\r\n            </div>\r\n            <di" +
                    "v class=\"swda-form-group\">\r\n                <label>软件描述</label>\r\n               " +
                    " ");
            parameterContainer.Controls[2].RenderControl(@__w);
            this.WriteUTF8ResourceString(@__w, 271960, 472, false);
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n                <small>可以输入图标的网络地址</small>\r\n            </div>\r\n            <di" +
                    "v class=\"swda-form-group\">\r\n                <label>或上传图标（JPG/PNG/GIF，最大2MB）</lab" +
                    "el>\r\n                ");
            parameterContainer.Controls[4].RenderControl(@__w);
            this.WriteUTF8ResourceString(@__w, 272432, 2075, false);
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write("\r\n                    <small>可以输入外部下载地址（适用于所有平台的通用版本）</small>\r\n                </" +
                    "div>\r\n                <div class=\"swda-form-group\">\r\n                    <label>" +
                    "或上传软件文件（最大500MB）</label>\r\n                    ");
            parameterContainer.Controls[6].RenderControl(@__w);
            this.WriteUTF8ResourceString(@__w, 274507, 339, false);
            parameterContainer.Controls[7].RenderControl(@__w);
            @__w.Write("\r\n                    <small>Windows 平台专用下载地址</small>\r\n                </div>\r\n  " +
                    "              <div class=\"swda-form-group\">\r\n                    <label>或上传 Wind" +
                    "ows 版本文件（最大500MB）</label>\r\n                    ");
            parameterContainer.Controls[8].RenderControl(@__w);
            this.WriteUTF8ResourceString(@__w, 274846, 318, false);
            parameterContainer.Controls[9].RenderControl(@__w);
            @__w.Write("\r\n                    <small>macOS 平台专用下载地址</small>\r\n                </div>\r\n    " +
                    "            <div class=\"swda-form-group\">\r\n                    <label>或上传 macOS " +
                    "版本文件（最大500MB）</label>\r\n                    ");
            parameterContainer.Controls[10].RenderControl(@__w);
            this.WriteUTF8ResourceString(@__w, 275164, 316, false);
            parameterContainer.Controls[11].RenderControl(@__w);
            @__w.Write("\r\n                    <small>Linux 平台专用下载地址</small>\r\n                </div>\r\n    " +
                    "            <div class=\"swda-form-group\">\r\n                    <label>或上传 Linux " +
                    "版本文件（最大500MB）</label>\r\n                    ");
            parameterContainer.Controls[12].RenderControl(@__w);
            @__w.Write("\r\n                    <small>支持 .deb、.rpm、.tar.gz、.AppImage 等 Linux 安装包格式</small>" +
                    "\r\n                </div>\r\n            </div>\r\n        </div>\r\n\r\n        <div cla" +
                    "ss=\"swda-actions\">\r\n            ");
            parameterContainer.Controls[13].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[14].RenderControl(@__w);
            this.WriteUTF8ResourceString(@__w, 275480, 1309, true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(teacher_softwaredownloadadd_aspx @__ctrl) {
            
            #line 1 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__ctrl.MasterPageFile = "~/teacher/Teach.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 280 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            this.AddContentTemplate("Content", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\inetpub\wwwroot\LearnSite\teacher\softwaredownloadadd.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.teacher_softwaredownloadadd_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.teacher_softwaredownloadadd_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -145199514;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
