//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9066
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "2.0.50727.9062")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_ge_y3e8z {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_ge_y3e8z() {
        }
        
        static object Create_ASP_student_create_autonomic_tables_aspx() {
            return new ASP.student_create_autonomic_tables_aspx();
        }
        
        static object Create_ASP_student_program_aspx() {
            return new ASP.student_program_aspx();
        }
        
        static object Create_ASP_student_pysolve_aspx() {
            return new ASP.student_pysolve_aspx();
        }
        
        static object Create_ASP_student_word_aspx() {
            return new ASP.student_word_aspx();
        }
        
        static object Create_ASP_student_uploadwork_aspx() {
            return new ASP.student_uploadwork_aspx();
        }
        
        static object Create_ASP_student_allfinger_aspx() {
            return new ASP.student_allfinger_aspx();
        }
        
        static object Create_ASP_student_uploadgroup_aspx() {
            return new ASP.student_uploadgroup_aspx();
        }
        
        static object Create_ASP_student_summary_aspx() {
            return new ASP.student_summary_aspx();
        }
        
        static object Create_ASP_student_htmleditor_aspx() {
            return new ASP.student_htmleditor_aspx();
        }
        
        static object Create_ASP_student_showcourse_new_aspx() {
            return new ASP.student_showcourse_new_aspx();
        }
        
        static object Create_ASP_student_autonomic_aspx() {
            return new ASP.student_autonomic_aspx();
        }
        
        static object Create_ASP_student_autoupload_aspx() {
            return new ASP.student_autoupload_aspx();
        }
    }
}
