#pragma checksum "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "DD8DEAB091C4CC4B047F59DA62692354"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9066
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 284 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 281 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 283 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 279 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 285 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 276 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 278 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 275 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 1 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 282 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 286 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 277 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 280 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 289 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class student_downfile_aspx : global::Student_downfile, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        
        #line 1532 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanErrorTitle;
        
        #line default
        #line hidden
        
        
        #line 1535 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanErrorMessage;
        
        #line default
        #line hidden
        
        
        #line 1528 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divPanelError;
        
        #line default
        #line hidden
        
        
        #line 1549 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanFileType;
        
        #line default
        #line hidden
        
        
        #line 1554 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanFileName;
        
        #line default
        #line hidden
        
        
        #line 1562 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanFileSize;
        
        #line default
        #line hidden
        
        
        #line 1569 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanCreateTime;
        
        #line default
        #line hidden
        
        
        #line 1576 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanFolderId;
        
        #line default
        #line hidden
        
        
        #line 1583 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanUploader;
        
        #line default
        #line hidden
        
        
        #line 1591 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.WebControls.HyperLink HLDownload;
        
        #line default
        #line hidden
        
        
        #line 1595 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.WebControls.Button BtnLike;
        
        #line default
        #line hidden
        
        
        #line 1599 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanLikeCount;
        
        #line default
        #line hidden
        
        
        #line 1602 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.WebControls.Button BtnFavorite;
        
        #line default
        #line hidden
        
        
        #line 1606 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanFavCount;
        
        #line default
        #line hidden
        
        
        #line 1613 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanActionMsg;
        
        #line default
        #line hidden
        
        
        #line 1611 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divActionMsg;
        
        #line default
        #line hidden
        
        
        #line 1624 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.WebControls.Repeater RptRelated;
        
        #line default
        #line hidden
        
        
        #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divPanelResource;
        
        #line default
        #line hidden
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        
        #line 4 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
                       
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            EnsureTables();
            LoadResourceData();
            LoadRelatedResources();
        }
    }
    
    protected void Page_PreRender(object sender, EventArgs e)
    {
        if (!string.IsNullOrEmpty(LabelFid.Text))
        {
            LoadLikeCount();
            LoadFavoriteCount();
            CheckUserActions();
        }
    }
    
    // 加载资源数据
    private void LoadResourceData()
    {
        string fid = Request.QueryString["fid"];
        if (string.IsNullOrEmpty(fid))
        {
            ShowError("缺少资源ID参数", "请在URL中提供 fid 参数，例如：downfile.aspx?fid=1");
            return;
        }
        
        LabelFid.Text = fid;
        
        // 调试模式
        bool debugMode = Request.QueryString["debug"] == "1";
        System.Text.StringBuilder debugInfo = new System.Text.StringBuilder();
        
        try
        {
            string connStr = GetConnectionString();
            using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(connStr))
            {
                conn.Open();
                
                if (debugMode)
                {
                    debugInfo.Append("<div style='background: #fef3c7; border: 1px solid #fde68a; padding: 16px; margin: 16px 0; border-radius: 8px;'>");
                    debugInfo.Append("<h3 style='margin: 0 0 12px 0; color: #92400e;'>🔍 调试信息</h3>");
                    debugInfo.Append("<p style='margin: 4px 0; color: #92400e;'><strong>请求的资源ID:</strong> " + fid + "</p>");
                }
                
                // 获取所有表
                System.Collections.Generic.List<string> allTables = new System.Collections.Generic.List<string>();
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                    "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' ORDER BY TABLE_NAME", conn))
                {
                    using (System.Data.SqlClient.SqlDataReader reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            allTables.Add(reader["TABLE_NAME"].ToString());
                        }
                    }
                }
                
                if (debugMode)
                {
                    debugInfo.Append("<p style='margin: 4px 0; color: #92400e;'><strong>数据库中的所有表:</strong> " + string.Join(", ", allTables.ToArray()) + "</p>");
                }
                
                // 尝试多个可能的表和字段组合
                bool found = false;
                System.Collections.Generic.List<string> attemptedTables = new System.Collections.Generic.List<string>();
                
                // 定义要尝试的表和字段映射
                string[][] tableMappings = new string[][] {
                    new string[] { "Files", "FileId", "FileName", "FileSize", "CreateTime", "RelativePath", "UserSnum", "FolderId" },
                    new string[] { "Filelist", "Fid", "Ftitle", "Fsize", "Fdate", "Furl", "Fauthor", "Fclass" },
                    new string[] { "Downfile", "Did", "Dtitle", "Dsize", "Ddate", "Durl", "Dauthor", "Dtype" },
                    new string[] { "Resources", "Rid", "Rtitle", "Rsize", "Rdate", "Rurl", "Rauthor", "Rtype" },
                    new string[] { "Homework", "Hid", "Htitle", "Hsize", "Hdate", "Hurl", "Hauthor", "Htype" },
                    new string[] { "Works", "Wid", "Wtitle", "Wsize", "Wdate", "Wurl", "Wauthor", "Wtype" },
                    // 添加更多可能的表结构
                    new string[] { "OnlineResources", "id", "title", "size", "date", "url", "author", "type" },
                    new string[] { "OnlineResource", "id", "title", "size", "date", "url", "author", "type" },
                    new string[] { "Zaixian", "id", "title", "size", "date", "url", "author", "type" },
                    new string[] { "Resource", "id", "title", "size", "date", "url", "author", "category" },
                    // 通用ID字段的表
                    new string[] { "GenericTable", "id", "name", "size", "createtime", "path", "user", "folder" }
                };
                
                foreach (string[] mapping in tableMappings)
                {
                    string tableName = mapping[0];
                    string idField = mapping[1];
                    
                    if (!TableExists(conn, tableName)) continue;
                    
                    attemptedTables.Add(tableName);
                    
                    if (debugMode)
                    {
                        // 检查表中的记录数
                        int recordCount = 0;
                        using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                            "SELECT COUNT(*) FROM [" + tableName + "]", conn))
                        {
                            recordCount = Convert.ToInt32(cmd.ExecuteScalar());
                        }
                        debugInfo.Append("<p style='margin: 4px 0; color: #92400e;'><strong>检查表 " + tableName + ":</strong> " + recordCount + " 条记录</p>");
                    }
                    
                    found = TryLoadFromTableWithMapping(conn, fid, mapping, debugMode, debugInfo);
                    
                    if (found)
                    {
                        if (debugMode)
                        {
                            debugInfo.Append("<p style='margin: 4px 0; color: #16a34a; font-weight: 600;'>✅ 成功从表 " + tableName + " 加载资源！</p>");
                            debugInfo.Append("</div>");
                            
                            // 在页面顶部显示调试信息
                            System.Web.UI.LiteralControl debugControl = new System.Web.UI.LiteralControl(debugInfo.ToString());
                            this.Page.Form.Controls.AddAt(0, debugControl);
                        }
                        break;
                    }
                }
                
                // 如果预定义的表都没找到，尝试自动发现表
                if (!found)
                {
                    if (debugMode)
                    {
                        debugInfo.Append("<p style='margin: 4px 0; color: #f59e0b; font-weight: 600;'>⚠️ 预定义表中未找到，尝试自动发现...</p>");
                    }
                    
                    found = TryAutoDiscoverTable(conn, fid, debugMode, debugInfo, attemptedTables);
                    
                    if (found && debugMode)
                    {
                        debugInfo.Append("<p style='margin: 4px 0; color: #16a34a; font-weight: 600;'>✅ 自动发现成功！</p>");
                        debugInfo.Append("</div>");
                        System.Web.UI.LiteralControl debugControl = new System.Web.UI.LiteralControl(debugInfo.ToString());
                        this.Page.Form.Controls.AddAt(0, debugControl);
                    }
                }
                
                if (!found)
                {
                    if (debugMode)
                    {
                        debugInfo.Append("<p style='margin: 4px 0; color: #dc2626; font-weight: 600;'>❌ 未找到资源</p>");
                        debugInfo.Append("<p style='margin: 4px 0; color: #92400e;'><strong>已尝试的表:</strong> " + string.Join(", ", attemptedTables.ToArray()) + "</p>");
                        debugInfo.Append("</div>");
                    }
                    
                    ShowResourceNotFoundError(conn, fid, debugMode ? debugInfo.ToString() : "");
                }
            }
        }
        catch (Exception ex)
        {
            string errorMsg = ex.Message + "<br/><br/>堆栈跟踪：<br/>" + ex.StackTrace.Replace("\n", "<br/>");
            if (debugMode && debugInfo.Length > 0)
            {
                errorMsg = debugInfo.ToString() + "<br/><br/>" + errorMsg;
            }
            ShowError("加载失败", errorMsg);
        }
    }
    
    // 尝试从指定表加载数据（使用字段映射）
    private bool TryLoadFromTableWithMapping(System.Data.SqlClient.SqlConnection conn, string fid, 
        string[] mapping, bool debugMode, System.Text.StringBuilder debugInfo)
    {
        string tableName = mapping[0];
        string idField = mapping[1];
        
        try
        {
            // 获取表的所有列
            System.Collections.Generic.List<string> columns = new System.Collections.Generic.List<string>();
            using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@tableName", conn))
            {
                cmd.Parameters.AddWithValue("@tableName", tableName);
                using (System.Data.SqlClient.SqlDataReader reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        columns.Add(reader["COLUMN_NAME"].ToString());
                    }
                }
            }
            
            if (debugMode)
            {
                debugInfo.Append("<p style='margin: 4px 0 4px 20px; color: #92400e; font-size: 13px;'>表 " + tableName + " 的列: " + string.Join(", ", columns.ToArray()) + "</p>");
            }
            
            // 检查ID字段是否存在
            bool hasIdField = false;
            foreach (string col in columns)
            {
                if (col.Equals(idField, StringComparison.OrdinalIgnoreCase))
                {
                    hasIdField = true;
                    break;
                }
            }
            
            if (!hasIdField)
            {
                if (debugMode)
                {
                    debugInfo.Append("<p style='margin: 4px 0 4px 20px; color: #dc2626; font-size: 13px;'>❌ 表中没有ID字段: " + idField + "</p>");
                }
                return false;
            }
            
            // 查询数据
            string query = "SELECT * FROM [" + tableName + "] WHERE [" + idField + "]=@fid";
            using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(query, conn))
            {
                cmd.Parameters.AddWithValue("@fid", fid);
                
                if (debugMode)
                {
                    debugInfo.Append("<p style='margin: 4px 0 4px 20px; color: #92400e; font-size: 13px;'>执行查询: " + query.Replace("@fid", fid) + "</p>");
                }
                
                using (System.Data.SqlClient.SqlDataReader reader = cmd.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        BindResourceDataFromReader(reader, tableName);
                        return true;
                    }
                    else
                    {
                        if (debugMode)
                        {
                            debugInfo.Append("<p style='margin: 4px 0 4px 20px; color: #dc2626; font-size: 13px;'>❌ 查询无结果</p>");
                        }
                    }
                }
            }
        }
        catch (Exception ex)
        {
            if (debugMode)
            {
                debugInfo.Append("<p style='margin: 4px 0 4px 20px; color: #dc2626; font-size: 13px;'>❌ 错误: " + ex.Message + "</p>");
            }
            System.Diagnostics.Debug.WriteLine("尝试从表 " + tableName + " 加载失败: " + ex.Message);
        }
        
        return false;
    }
    
    // 检查表是否存在
    private bool TableExists(System.Data.SqlClient.SqlConnection conn, string tableName)
    {
        try
        {
            using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME=@tableName", conn))
            {
                cmd.Parameters.AddWithValue("@tableName", tableName);
                return Convert.ToInt32(cmd.ExecuteScalar()) > 0;
            }
        }
        catch { return false; }
    }

    // 从 DataReader 绑定数据（智能字段匹配）
    private void BindResourceDataFromReader(System.Data.SqlClient.SqlDataReader reader, string tableName)
    {
        try
        {
            // 文件名字段
            string[] nameFields = new string[] { "FileName", "Ftitle", "Dtitle", "Rtitle", "Title", "Name" };
            foreach (string field in nameFields)
            {
                if (HasColumn(reader, field) && reader[field] != DBNull.Value)
                {
                    spanFileName.InnerText = reader[field].ToString();
                    break;
                }
            }
            
            // 文件大小字段
            string[] sizeFields = new string[] { "FileSize", "Fsize", "Dsize", "Rsize", "Size" };
            foreach (string field in sizeFields)
            {
                if (HasColumn(reader, field) && reader[field] != DBNull.Value)
                {
                    long size = Convert.ToInt64(reader[field]);
                    spanFileSize.InnerText = FormatFileSize(size);
                    break;
                }
            }
            
            // 创建时间字段
            string[] dateFields = new string[] { "CreateTime", "Fdate", "Ddate", "Rdate", "Date", "CreateDate", "UploadDate" };
            foreach (string field in dateFields)
            {
                if (HasColumn(reader, field) && reader[field] != DBNull.Value)
                {
                    spanCreateTime.InnerText = Convert.ToDateTime(reader[field]).ToString("yyyy-MM-dd HH:mm");
                    break;
                }
            }
            
            // 文件夹/分类字段
            string[] folderFields = new string[] { "FolderId", "Fclass", "Dtype", "Rtype", "Category", "Type" };
            foreach (string field in folderFields)
            {
                if (HasColumn(reader, field) && reader[field] != DBNull.Value)
                {
                    spanFolderId.InnerText = reader[field].ToString();
                    break;
                }
            }
            
            // 上传者字段
            string[] authorFields = new string[] { "UserSnum", "Fauthor", "Dauthor", "Rauthor", "Author", "Uploader" };
            foreach (string field in authorFields)
            {
                if (HasColumn(reader, field) && reader[field] != DBNull.Value)
                {
                    spanUploader.InnerText = reader[field].ToString();
                    break;
                }
            }
            
            // 下载路径字段
            string[] urlFields = new string[] { "RelativePath", "Furl", "Durl", "Rurl", "Url", "Path", "FilePath" };
            foreach (string field in urlFields)
            {
                if (HasColumn(reader, field) && reader[field] != DBNull.Value)
                {
                    string path = reader[field].ToString();
                    if (!string.IsNullOrEmpty(path))
                    {
                        HLDownload.NavigateUrl = path.StartsWith("/") ? path : "/" + path;
                        HLDownload.Visible = true;
                        
                        // 获取文件扩展名
                        string ext = System.IO.Path.GetExtension(path).ToLower();
                        spanFileType.InnerText = GetFileTypeIcon(ext);
                        break;
                    }
                }
            }
            
            // 如果没有找到文件类型，使用默认图标
            if (string.IsNullOrEmpty(spanFileType.InnerText))
            {
                spanFileType.InnerText = "📄";
            }
            
            divPanelResource.Visible = true;
            divPanelError.Visible = false;
            
            System.Diagnostics.Debug.WriteLine("成功从表 " + tableName + " 加载资源");
        }
        catch (Exception ex)
        {
            ShowError("数据绑定失败", ex.Message);
        }
    }
    
    // 检查列是否存在
    private bool HasColumn(System.Data.SqlClient.SqlDataReader reader, string columnName)
    {
        try
        {
            for (int i = 0; i < reader.FieldCount; i++)
            {
                if (reader.GetName(i).Equals(columnName, StringComparison.OrdinalIgnoreCase))
                    return true;
            }
        }
        catch { }
        return false;
    }
    
    // 自动发现包含指定ID的表
    private bool TryAutoDiscoverTable(System.Data.SqlClient.SqlConnection conn, string fid, 
        bool debugMode, System.Text.StringBuilder debugInfo, System.Collections.Generic.List<string> attemptedTables)
    {
        try
        {
            // 获取所有表
            System.Collections.Generic.List<string> allTables = new System.Collections.Generic.List<string>();
            using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' ORDER BY TABLE_NAME", conn))
            {
                using (System.Data.SqlClient.SqlDataReader reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        string tableName = reader["TABLE_NAME"].ToString();
                        // 跳过已经尝试过的表
                        if (!attemptedTables.Contains(tableName))
                        {
                            allTables.Add(tableName);
                        }
                    }
                }
            }
            
            // 遍历所有表
            foreach (string tableName in allTables)
            {
                try
                {
                    // 获取表的列
                    System.Collections.Generic.List<string> columns = new System.Collections.Generic.List<string>();
                    using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                        "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@tableName ORDER BY ORDINAL_POSITION", conn))
                    {
                        cmd.Parameters.AddWithValue("@tableName", tableName);
                        using (System.Data.SqlClient.SqlDataReader reader = cmd.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                columns.Add(reader["COLUMN_NAME"].ToString());
                            }
                        }
                    }
                    
                    if (columns.Count == 0) continue;
                    
                    // 查找可能的ID字段
                    string idField = null;
                    string[] possibleIdFields = new string[] { "id", "Id", "ID", "序号", "编号" };
                    foreach (string possibleId in possibleIdFields)
                    {
                        foreach (string col in columns)
                        {
                            if (col.Equals(possibleId, StringComparison.OrdinalIgnoreCase) ||
                                col.EndsWith("id", StringComparison.OrdinalIgnoreCase) ||
                                col.EndsWith("Id") ||
                                col.EndsWith("ID"))
                            {
                                idField = col;
                                break;
                            }
                        }
                        if (idField != null) break;
                    }
                    
                    // 如果没有找到ID字段，使用第一列
                    if (idField == null && columns.Count > 0)
                    {
                        idField = columns[0];
                    }
                    
                    if (debugMode)
                    {
                        debugInfo.Append("<p style='margin: 4px 0 4px 20px; color: #92400e; font-size: 13px;'>尝试表 " + tableName + " (ID字段: " + idField + ")</p>");
                    }
                    
                    // 尝试查询
                    string query = "SELECT * FROM [" + tableName + "] WHERE [" + idField + "]=@fid";
                    using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(query, conn))
                    {
                        cmd.Parameters.AddWithValue("@fid", fid);
                        using (System.Data.SqlClient.SqlDataReader reader = cmd.ExecuteReader())
                        {
                            if (reader.Read())
                            {
                                if (debugMode)
                                {
                                    debugInfo.Append("<p style='margin: 4px 0 4px 20px; color: #16a34a; font-size: 13px;'>✅ 在表 " + tableName + " 中找到记录！</p>");
                                }
                                
                                BindResourceDataFromReader(reader, tableName);
                                return true;
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    if (debugMode)
                    {
                        debugInfo.Append("<p style='margin: 4px 0 4px 20px; color: #dc2626; font-size: 13px;'>❌ 表 " + tableName + " 错误: " + ex.Message + "</p>");
                    }
                }
            }
        }
        catch (Exception ex)
        {
            if (debugMode)
            {
                debugInfo.Append("<p style='margin: 4px 0; color: #dc2626;'>自动发现失败: " + ex.Message + "</p>");
            }
        }
        
        return false;
    }
    
    // 显示资源不存在错误，并列出可用资源
    private void ShowResourceNotFoundError(System.Data.SqlClient.SqlConnection conn, string requestedFid, string debugInfo)
    {
        System.Text.StringBuilder errorMsg = new System.Text.StringBuilder();
        errorMsg.Append("<div style='text-align: left;'>");
        
        // 如果有调试信息，先显示
        if (!string.IsNullOrEmpty(debugInfo))
        {
            errorMsg.Append(debugInfo);
        }
        
        errorMsg.Append("<p style='margin-bottom: 20px;'>未找到ID为 <strong>" + requestedFid + "</strong> 的资源。</p>");
        
        try
        {
            bool foundAnyResources = false;
            
            // 尝试从多个表中查找资源
            string[] tables = new string[] { "Files", "Filelist", "Downfile", "Resources" };
            string[] idFields = new string[] { "FileId", "Fid", "Did", "Rid" };
            string[] nameFields = new string[] { "FileName", "Ftitle", "Dtitle", "Rtitle" };
            string[] dateFields = new string[] { "CreateTime", "Fdate", "Ddate", "Rdate" };
            
            for (int i = 0; i < tables.Length; i++)
            {
                if (!TableExists(conn, tables[i])) continue;
                
                try
                {
                    // 检查表中是否有数据
                    string countQuery = "SELECT COUNT(*) FROM [" + tables[i] + "]";
                    using (System.Data.SqlClient.SqlCommand countCmd = new System.Data.SqlClient.SqlCommand(countQuery, conn))
                    {
                        int count = Convert.ToInt32(countCmd.ExecuteScalar());
                        if (count == 0) continue;
                    }
                    
                    // 获取资源列表
                    string query = "SELECT TOP 10 * FROM [" + tables[i] + "] ORDER BY 1 DESC";
                    using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(query, conn))
                    {
                        using (System.Data.SqlClient.SqlDataReader reader = cmd.ExecuteReader())
                        {
                            if (reader.HasRows)
                            {
                                if (!foundAnyResources)
                                {
                                    errorMsg.Append("<p style='font-weight: 600; color: #1e293b; margin-bottom: 12px;'>📋 可用的资源：</p>");
                                    errorMsg.Append("<div style='background: #f8fafc; border-radius: 8px; padding: 16px; border: 1px solid #e2e8f0;'>");
                                    foundAnyResources = true;
                                }
                                
                                errorMsg.Append("<p style='font-size: 13px; color: #667eea; font-weight: 600; margin: 12px 0 8px 0;'>来自表: " + tables[i] + "</p>");
                                
                                int resourceCount = 0;
                                while (reader.Read() && resourceCount < 10)
                                {
                                    resourceCount++;
                                    
                                    // 获取ID
                                    string fileId = "";
                                    if (HasColumn(reader, idFields[i]))
                                        fileId = reader[idFields[i]].ToString();
                                    else if (reader.FieldCount > 0)
                                        fileId = reader[0].ToString();
                                    
                                    // 获取文件名
                                    string fileName = "";
                                    if (HasColumn(reader, nameFields[i]))
                                        fileName = reader[nameFields[i]].ToString();
                                    else if (HasColumn(reader, "Title"))
                                        fileName = reader["Title"].ToString();
                                    else if (HasColumn(reader, "Name"))
                                        fileName = reader["Name"].ToString();
                                    
                                    // 获取日期
                                    string createTime = "";
                                    if (HasColumn(reader, dateFields[i]) && reader[dateFields[i]] != DBNull.Value)
                                    {
                                        createTime = Convert.ToDateTime(reader[dateFields[i]]).ToString("yyyy-MM-dd");
                                    }
                                    
                                    if (string.IsNullOrEmpty(fileName))
                                        fileName = "未命名资源";
                                    
                                    errorMsg.Append("<div style='padding: 10px; margin-bottom: 8px; background: #fff; border-radius: 6px; border: 1px solid #e2e8f0;'>");
                                    errorMsg.Append("<a href='downfile.aspx?fid=" + fileId + "' style='color: #667eea; text-decoration: none; font-weight: 600; display: block; margin-bottom: 4px;'>");
                                    errorMsg.Append("📄 " + fileName);
                                    errorMsg.Append("</a>");
                                    errorMsg.Append("<span style='font-size: 12px; color: #64748b;'>ID: " + fileId);
                                    if (!string.IsNullOrEmpty(createTime))
                                    {
                                        errorMsg.Append(" | 创建时间: " + createTime);
                                    }
                                    errorMsg.Append("</span>");
                                    errorMsg.Append("</div>");
                                }
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine("查询表 " + tables[i] + " 失败: " + ex.Message);
                }
            }
            
            if (foundAnyResources)
            {
                errorMsg.Append("</div>");
            }
            else
            {
                errorMsg.Append("<div style='background: #fef3c7; border: 1px solid #fde68a; border-radius: 8px; padding: 16px; margin-top: 16px;'>");
                errorMsg.Append("<p style='color: #92400e; margin: 0;'><strong>⚠️ 提示：</strong>数据库中没有找到任何资源数据。</p>");
                errorMsg.Append("<p style='color: #92400e; margin: 8px 0 0 0;'>请先在数据库中添加资源数据，或联系管理员。</p>");
                errorMsg.Append("<p style='color: #92400e; margin: 8px 0 0 0; font-size: 12px;'>已检查的表: Files, Filelist, Downfile, Resources</p>");
                errorMsg.Append("</div>");
            }
        }
        catch (Exception ex)
        {
            errorMsg.Append("<p style='color: #dc2626; margin-top: 12px;'>获取资源列表失败: " + ex.Message + "</p>");
        }
        
        errorMsg.Append("<div style='margin-top: 24px; text-align: center;'>");
        errorMsg.Append("<a href='myfile.aspx' style='display: inline-block; padding: 10px 24px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #fff; border-radius: 8px; text-decoration: none; font-weight: 600;'>← 返回资源列表</a>");
        errorMsg.Append("</div>");
        errorMsg.Append("</div>");
        
        ShowError("资源不存在", errorMsg.ToString());
    }

    
    // 格式化文件大小
    private string FormatFileSize(long bytes)
    {
        if (bytes < 1024) return bytes + " B";
        if (bytes < 1024 * 1024) return (bytes / 1024.0).ToString("F2") + " KB";
        if (bytes < 1024 * 1024 * 1024) return (bytes / 1024.0 / 1024.0).ToString("F2") + " MB";
        return (bytes / 1024.0 / 1024.0 / 1024.0).ToString("F2") + " GB";
    }
    
    // 获取文件类型图标
    private string GetFileTypeIcon(string ext)
    {
        switch (ext)
        {
            case ".pdf": return "📄 PDF文档";
            case ".doc": case ".docx": return "📝 Word文档";
            case ".xls": case ".xlsx": return "📊 Excel表格";
            case ".ppt": case ".pptx": return "📽️ PPT演示";
            case ".zip": case ".rar": case ".7z": return "📦 压缩文件";
            case ".jpg": case ".jpeg": case ".png": case ".gif": return "🖼️ 图片文件";
            case ".mp4": case ".avi": case ".mov": return "🎬 视频文件";
            case ".mp3": case ".wav": return "🎵 音频文件";
            case ".txt": return "📃 文本文件";
            case ".html": case ".htm": return "🌐 网页文件";
            default: return "📁 " + ext.TrimStart('.');
        }
    }
    
    // 显示错误
    private void ShowError(string title, string message)
    {
        spanErrorTitle.InnerText = title;
        spanErrorMessage.InnerHtml = message;
        divPanelError.Visible = true;
        divPanelResource.Visible = false;
    }
    
    // 加载相关资源
    private void LoadRelatedResources()
    {
        try
        {
            string connStr = GetConnectionString();
            using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(connStr))
            {
                conn.Open();
                
                // 尝试从多个表中加载资源
                System.Collections.Generic.List<RelatedResource> resources = new System.Collections.Generic.List<RelatedResource>();
                
                // 定义表和字段映射
                string[][] tableMappings = new string[][] {
                    new string[] { "Files", "FileId", "FileName", "CreateTime" },
                    new string[] { "Filelist", "Fid", "Ftitle", "Fdate" },
                    new string[] { "Downfile", "Did", "Dtitle", "Ddate" },
                    new string[] { "Resources", "Rid", "Rtitle", "Rdate" },
                    new string[] { "Homework", "Hid", "Htitle", "Hdate" },
                    new string[] { "Works", "Wid", "Wtitle", "Wdate" }
                };
                
                foreach (string[] mapping in tableMappings)
                {
                    string tableName = mapping[0];
                    string idField = mapping[1];
                    string nameField = mapping[2];
                    string dateField = mapping[3];
                    
                    if (!TableExists(conn, tableName)) continue;
                    
                    try
                    {
                        // 检查字段是否存在
                        System.Collections.Generic.List<string> columns = new System.Collections.Generic.List<string>();
                        using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                            "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@tableName", conn))
                        {
                            cmd.Parameters.AddWithValue("@tableName", tableName);
                            using (System.Data.SqlClient.SqlDataReader reader = cmd.ExecuteReader())
                            {
                                while (reader.Read())
                                {
                                    columns.Add(reader["COLUMN_NAME"].ToString());
                                }
                            }
                        }
                        
                        // 检查必需字段是否存在
                        bool hasIdField = false;
                        bool hasNameField = false;
                        foreach (string col in columns)
                        {
                            if (col.Equals(idField, StringComparison.OrdinalIgnoreCase))
                                hasIdField = true;
                            if (col.Equals(nameField, StringComparison.OrdinalIgnoreCase))
                                hasNameField = true;
                        }
                        
                        if (!hasIdField || !hasNameField) continue;
                        
                        // 构建查询
                        string orderBy = "";
                        foreach (string col in columns)
                        {
                            if (col.Equals(dateField, StringComparison.OrdinalIgnoreCase))
                            {
                                orderBy = " ORDER BY [" + dateField + "] DESC";
                                break;
                            }
                        }
                        
                        if (string.IsNullOrEmpty(orderBy))
                        {
                            orderBy = " ORDER BY [" + idField + "] DESC";
                        }
                        
                        string query = "SELECT TOP 10 [" + idField + "] as FileId, [" + nameField + "] as FileName FROM [" + tableName + "]" + orderBy;
                        
                        using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(query, conn))
                        {
                            using (System.Data.SqlClient.SqlDataReader reader = cmd.ExecuteReader())
                            {
                                while (reader.Read())
                                {
                                    RelatedResource resource = new RelatedResource();
                                    resource.FileId = reader["FileId"].ToString();
                                    resource.FileName = reader["FileName"].ToString();
                                    resources.Add(resource);
                                }
                            }
                        }
                        
                        // 如果已经找到资源，就不再查询其他表
                        if (resources.Count > 0) break;
                    }
                    catch (Exception ex)
                    {
                        System.Diagnostics.Debug.WriteLine("从表 " + tableName + " 加载相关资源失败: " + ex.Message);
                    }
                }
                
                // 绑定数据
                if (resources.Count > 0)
                {
                    RptRelated.DataSource = resources;
                    RptRelated.DataBind();
                }
            }
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine("加载相关资源失败: " + ex.Message);
        }
    }
    
    // 相关资源类
    public class RelatedResource
    {
        private string fileId;
        private string fileName;
        
        public string FileId
        {
            get { return fileId; }
            set { fileId = value; }
        }
        
        public string FileName
        {
            get { return fileName; }
            set { fileName = value; }
        }
    }
    
    // 点赞
    protected void BtnLike_Click(object sender, EventArgs e)
    {
        string sid = GetStudentId();
        if (string.IsNullOrEmpty(sid))
        {
            spanActionMsg.InnerText = "请先登录";
            divActionMsg.Visible = true;
            return;
        }
        
        try
        {
            string connStr = GetConnectionString();
            using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(connStr))
            {
                conn.Open();
                
                // 检查是否已点赞
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                    "SELECT COUNT(*) FROM ResourceLikes WHERE Fid=@fid AND Sid=@sid", conn))
                {
                    cmd.Parameters.AddWithValue("@fid", LabelFid.Text);
                    cmd.Parameters.AddWithValue("@sid", sid);
                    if (Convert.ToInt32(cmd.ExecuteScalar()) > 0)
                    {
                        spanActionMsg.InnerText = "您已经点赞过了";
                        divActionMsg.Visible = true;
                        return;
                    }
                }
                
                // 添加点赞
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                    "INSERT INTO ResourceLikes (Fid, Sid, Ldate) VALUES (@fid, @sid, GETDATE())", conn))
                {
                    cmd.Parameters.AddWithValue("@fid", LabelFid.Text);
                    cmd.Parameters.AddWithValue("@sid", sid);
                    cmd.ExecuteNonQuery();
                }
            }
            
            LoadLikeCount();
            BtnLike.Enabled = false;
            BtnLike.Text = "✓ 已点赞";
            spanActionMsg.InnerText = "点赞成功！";
            divActionMsg.Visible = true;
        }
        catch (Exception ex)
        {
            spanActionMsg.InnerText = "点赞失败：" + ex.Message;
            divActionMsg.Visible = true;
        }
    }
    
    // 收藏
    protected void BtnFavorite_Click(object sender, EventArgs e)
    {
        string sid = GetStudentId();
        if (string.IsNullOrEmpty(sid))
        {
            spanActionMsg.InnerText = "请先登录";
            divActionMsg.Visible = true;
            return;
        }
        
        try
        {
            string connStr = GetConnectionString();
            using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(connStr))
            {
                conn.Open();
                
                // 检查是否已收藏
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                    "SELECT COUNT(*) FROM ResourceFavorites WHERE Fid=@fid AND Sid=@sid", conn))
                {
                    cmd.Parameters.AddWithValue("@fid", LabelFid.Text);
                    cmd.Parameters.AddWithValue("@sid", sid);
                    if (Convert.ToInt32(cmd.ExecuteScalar()) > 0)
                    {
                        spanActionMsg.InnerText = "您已经收藏过了";
                        divActionMsg.Visible = true;
                        return;
                    }
                }
                
                // 添加收藏
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                    "INSERT INTO ResourceFavorites (Fid, Sid, Fdate) VALUES (@fid, @sid, GETDATE())", conn))
                {
                    cmd.Parameters.AddWithValue("@fid", LabelFid.Text);
                    cmd.Parameters.AddWithValue("@sid", sid);
                    cmd.ExecuteNonQuery();
                }
            }
            
            LoadFavoriteCount();
            BtnFavorite.Enabled = false;
            BtnFavorite.Text = "★ 已收藏";
            spanActionMsg.InnerText = "收藏成功！";
            divActionMsg.Visible = true;
        }
        catch (Exception ex)
        {
            spanActionMsg.InnerText = "收藏失败：" + ex.Message;
            divActionMsg.Visible = true;
        }
    }
    
    // 加载点赞数
    private void LoadLikeCount()
    {
        try
        {
            string connStr = GetConnectionString();
            using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(connStr))
            {
                conn.Open();
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                    "SELECT COUNT(*) FROM ResourceLikes WHERE Fid=@fid", conn))
                {
                    cmd.Parameters.AddWithValue("@fid", LabelFid.Text);
                    spanLikeCount.InnerText = cmd.ExecuteScalar().ToString();
                }
            }
        }
        catch { spanLikeCount.InnerText = "0"; }
    }
    
    // 加载收藏数
    private void LoadFavoriteCount()
    {
        try
        {
            string connStr = GetConnectionString();
            using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(connStr))
            {
                conn.Open();
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                    "SELECT COUNT(*) FROM ResourceFavorites WHERE Fid=@fid", conn))
                {
                    cmd.Parameters.AddWithValue("@fid", LabelFid.Text);
                    spanFavCount.InnerText = cmd.ExecuteScalar().ToString();
                }
            }
        }
        catch { spanFavCount.InnerText = "0"; }
    }
    
    // 检查用户操作状态
    private void CheckUserActions()
    {
        string sid = GetStudentId();
        if (string.IsNullOrEmpty(sid)) return;
        
        try
        {
            string connStr = GetConnectionString();
            using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(connStr))
            {
                conn.Open();
                
                // 检查点赞
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                    "SELECT COUNT(*) FROM ResourceLikes WHERE Fid=@fid AND Sid=@sid", conn))
                {
                    cmd.Parameters.AddWithValue("@fid", LabelFid.Text);
                    cmd.Parameters.AddWithValue("@sid", sid);
                    if (Convert.ToInt32(cmd.ExecuteScalar()) > 0)
                    {
                        BtnLike.Enabled = false;
                        BtnLike.Text = "✓ 已点赞";
                    }
                }
                
                // 检查收藏
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(
                    "SELECT COUNT(*) FROM ResourceFavorites WHERE Fid=@fid AND Sid=@sid", conn))
                {
                    cmd.Parameters.AddWithValue("@fid", LabelFid.Text);
                    cmd.Parameters.AddWithValue("@sid", sid);
                    if (Convert.ToInt32(cmd.ExecuteScalar()) > 0)
                    {
                        BtnFavorite.Enabled = false;
                        BtnFavorite.Text = "★ 已收藏";
                    }
                }
            }
        }
        catch { }
    }
    
    // 确保表存在
    private void EnsureTables()
    {
        try
        {
            string connStr = GetConnectionString();
            using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(connStr))
            {
                conn.Open();
                
                // 创建点赞表
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(@"
                    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='ResourceLikes' AND xtype='U')
                    CREATE TABLE ResourceLikes (
                        Lid INT IDENTITY(1,1) PRIMARY KEY,
                        Fid INT NOT NULL,
                        Sid VARCHAR(50) NOT NULL,
                        Ldate DATETIME NOT NULL
                    )", conn))
                {
                    cmd.ExecuteNonQuery();
                }
                
                // 创建收藏表
                using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(@"
                    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='ResourceFavorites' AND xtype='U')
                    CREATE TABLE ResourceFavorites (
                        Fvid INT IDENTITY(1,1) PRIMARY KEY,
                        Fid INT NOT NULL,
                        Sid VARCHAR(50) NOT NULL,
                        Fdate DATETIME NOT NULL
                    )", conn))
                {
                    cmd.ExecuteNonQuery();
                }
            }
        }
        catch { }
    }
    
    // 获取数据库连接字符串
    private string GetConnectionString()
    {
        try
        {
            return System.Configuration.ConfigurationManager.ConnectionStrings["SqlServer"].ConnectionString;
        }
        catch
        {
            return "";
        }
    }
    
    // 获取学生ID
    private string GetStudentId()
    {
        try
        {
            HttpCookie sc = Request.Cookies[LearnSite.Common.CookieHelp.stuCookieNname];
            if (sc != null && !string.IsNullOrEmpty(sc.Value))
            {
                string cookieVal = sc.Value;
                if (cookieVal.Contains("%"))
                {
                    try { cookieVal = HttpUtility.UrlDecode(cookieVal, System.Text.Encoding.UTF8); }
                    catch { }
                }
                
                Type ct = typeof(LearnSite.Common.CookieHelp).Assembly.GetType("LearnSite.Model.Cook");
                if (ct != null)
                {
                    object m = Activator.CreateInstance(ct);
                    System.Reflection.MethodInfo mi = ct.GetMethod("ToModel",
                        System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic |
                        System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Static);
                    if (mi != null) mi.Invoke(m, new object[] { cookieVal });
                    
                    System.Reflection.PropertyInfo pSnum = ct.GetProperty("Snum");
                    if (pSnum != null)
                    {
                        object v = pSnum.GetValue(m, null);
                        if (v != null && !string.IsNullOrEmpty(v.ToString()))
                            return v.ToString();
                    }
                    
                    System.Reflection.PropertyInfo pSid = ct.GetProperty("Sid");
                    if (pSid != null)
                    {
                        object v = pSid.GetValue(m, null);
                        if (v != null && !string.IsNullOrEmpty(v.ToString()))
                            return v.ToString();
                    }
                }
            }
        }
        catch { }
        return "";
    }

        #line default
        #line hidden
        
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public student_downfile_aspx() {
            string[] dependencies;
            ((global::Student_downfile)(this)).AppRelativeVirtualPath = "~/student/downfile.aspx";
            if ((global::ASP.student_downfile_aspx.@__initialized == false)) {
                global::ASP.student_downfile_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[2];
                dependencies[0] = "~/student/downfile.aspx";
                dependencies[1] = "~/student/Stud.master";
                global::ASP.student_downfile_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.student_downfile_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlspanErrorTitle() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1532 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            this.spanErrorTitle = @__ctrl;
            
            #line 1532 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "spanErrorTitle";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlspanErrorMessage() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1535 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            this.spanErrorMessage = @__ctrl;
            
            #line 1535 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "spanErrorMessage";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivPanelError() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1528 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            
            #line default
            #line hidden
            this.divPanelError = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 1528 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "divPanelError";
            
            #line default
            #line hidden
            
            #line 1528 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1528 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            <div class=\"error-card\">\r\n                <div class=\"error-icon\">❌" +
                        "</div>\r\n                <h2 class=\"error-title\">\r\n                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            
            #line 1528 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl1 = this.@__BuildControlspanErrorTitle();
            
            #line default
            #line hidden
            
            #line 1528 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 1528 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </h2>\r\n                <div class=\"error-message\">\r\n           " +
                        "         "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            
            #line 1528 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl2 = this.@__BuildControlspanErrorMessage();
            
            #line default
            #line hidden
            
            #line 1528 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 1528 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n                <a href=\"myfile.aspx\" class=\"btn-back\">" +
                        "← 返回资源列表</a>\r\n            </div>\r\n        "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlspanFileType() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1549 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            this.spanFileType = @__ctrl;
            
            #line 1549 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "spanFileType";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlspanFileName() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1554 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            this.spanFileName = @__ctrl;
            
            #line 1554 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "spanFileName";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlspanFileSize() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1562 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            this.spanFileSize = @__ctrl;
            
            #line 1562 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "spanFileSize";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlspanCreateTime() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1569 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            this.spanCreateTime = @__ctrl;
            
            #line 1569 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "spanCreateTime";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlspanFolderId() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1576 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            this.spanFolderId = @__ctrl;
            
            #line 1576 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "spanFolderId";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlspanUploader() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1583 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            this.spanUploader = @__ctrl;
            
            #line 1583 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "spanUploader";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControlHLDownload() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 1591 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            this.HLDownload = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 1591 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "HLDownload";
            
            #line default
            #line hidden
            
            #line 1591 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.CssClass = "btn btn-download";
            
            #line default
            #line hidden
            
            #line 1591 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1591 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            ⬇️ 下载资源\r\n                        "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnLike() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 1595 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.BtnLike = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 1595 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "BtnLike";
            
            #line default
            #line hidden
            
            #line 1595 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.Text = "👍 点赞";
            
            #line default
            #line hidden
            
            #line 1595 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.CssClass = "btn btn-like";
            
            #line default
            #line hidden
            
            #line 1595 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.Click -= new System.EventHandler(this.BtnLike_Click);
            
            #line default
            #line hidden
            
            #line 1595 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.Click += new System.EventHandler(this.BtnLike_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlspanLikeCount() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1599 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            this.spanLikeCount = @__ctrl;
            
            #line 1599 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "spanLikeCount";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1599 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("0"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnFavorite() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 1602 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.BtnFavorite = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 1602 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "BtnFavorite";
            
            #line default
            #line hidden
            
            #line 1602 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.Text = "⭐ 收藏";
            
            #line default
            #line hidden
            
            #line 1602 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.CssClass = "btn btn-favorite";
            
            #line default
            #line hidden
            
            #line 1602 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.Click -= new System.EventHandler(this.BtnFavorite_Click);
            
            #line default
            #line hidden
            
            #line 1602 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.Click += new System.EventHandler(this.BtnFavorite_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlspanFavCount() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1606 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            this.spanFavCount = @__ctrl;
            
            #line 1606 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "spanFavCount";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1606 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("0"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlspanActionMsg() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1613 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            
            #line default
            #line hidden
            this.spanActionMsg = @__ctrl;
            
            #line 1613 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "spanActionMsg";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivActionMsg() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1611 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            
            #line default
            #line hidden
            this.divActionMsg = @__ctrl;
            
            #line 1611 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "divActionMsg";
            
            #line default
            #line hidden
            
            #line 1611 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1611 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div class=\"action-msg\">\r\n                            "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            
            #line 1611 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl1 = this.@__BuildControlspanActionMsg();
            
            #line default
            #line hidden
            
            #line 1611 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 1611 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n                    "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control3() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 1627 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(3, 2);
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                                    <div class=\"related-item\">\r\n               " +
                    "                         <a href=\'downfile.aspx?fid=");
            @__ctrl.SetStaticString(1, "\'>\r\n                                            ");
            @__ctrl.SetStaticString(2, "\r\n                                        </a>\r\n                                 " +
                    "   </div>\r\n                                ");
            
            #line 1627 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control3);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBind__control3(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.RepeaterItem Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 1627 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 1627 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 1627 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            target.SetDataBoundString(0, System.Convert.ToString(Eval("FileId"), System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 1628 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            target.SetDataBoundString(1, System.Convert.ToString(Eval("FileName"), System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            
            #line 1624 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1624 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Repeater @__BuildControlRptRelated() {
            global::System.Web.UI.WebControls.Repeater @__ctrl;
            
            #line 1624 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Repeater();
            
            #line default
            #line hidden
            this.RptRelated = @__ctrl;
            
            #line 1624 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            
            #line default
            #line hidden
            
            #line 1624 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "RptRelated";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivPanelResource() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            
            #line default
            #line hidden
            this.divPanelResource = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "divPanelResource";
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(250136, 300, false));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl1 = this.@__BuildControlspanFileType();
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n                        \r\n                     " +
                        "   <!-- 文件名 -->\r\n                        <h1 class=\"file-name\">\r\n               " +
                        "             "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl2 = this.@__BuildControlspanFileName();
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(250436, 389, false));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl3;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl3 = this.@__BuildControlspanFileSize();
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(250825, 340, false));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl4;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl4 = this.@__BuildControlspanCreateTime();
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(251165, 337, false));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl5;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl5 = this.@__BuildControlspanFolderId();
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(251502, 337, false));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl6;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl6 = this.@__BuildControlspanUploader();
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(251839, 278, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl7;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl7 = this.@__BuildControlHLDownload();
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        \r\n                        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl8;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl8 = this.@__BuildControlBtnLike();
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        \r\n                        <span class=\"stat-badge\">\r\n  " +
                        "                          "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl9;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl9 = this.@__BuildControlspanLikeCount();
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(" 赞\r\n                        </span>\r\n                        \r\n                  " +
                        "      "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl10;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl10 = this.@__BuildControlBtnFavorite();
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        \r\n                        <span class=\"stat-badge\">\r\n  " +
                        "                          "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl11;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl11 = this.@__BuildControlspanFavCount();
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(" 收藏\r\n                        </span>\r\n                    </div>\r\n               " +
                        "     \r\n                    <!-- 操作消息 -->\r\n                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl12;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl12 = this.@__BuildControldivActionMsg();
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(252117, 368, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Repeater @__ctrl13;
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl13 = this.@__BuildControlRptRelated();
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            
            #line 1542 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(252485, 814, false));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabelFid() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 1655 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.LabelFid = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 1655 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.ID = "LabelFid";
            
            #line default
            #line hidden
            
            #line 1655 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
            
            #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(253299, 8452, false));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            
            #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl1 = this.@__BuildControldivPanelError();
            
            #line default
            #line hidden
            
            #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        \r\n        <!-- 资源内容面板 -->\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            
            #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl2 = this.@__BuildControldivPanelResource();
            
            #line default
            #line hidden
            
            #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n</div>\r\n\r\n<!-- 隐藏字段 -->\r\n"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl3;
            
            #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl3 = this.@__BuildControlLabelFid();
            
            #line default
            #line hidden
            
            #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(261751, 563, false));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(student_downfile_aspx @__ctrl) {
            
            #line 1 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__ctrl.MasterPageFile = "~/student/Stud.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 2 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            this.AddContentTemplate("Cphs", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\inetpub\wwwroot\LearnSite\student\downfile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            this.StyleSheetTheme = "Student";
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.student_downfile_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.student_downfile_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -713056241;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
