#pragma checksum "C:\inetpub\wwwroot\LearnSite\student\getnotices.aspx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "AE922427B3E0547A2FD57B879E679A2D"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9066
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 285 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 280 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 282 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 278 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 284 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 289 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 281 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 287 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 286 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 276 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 275 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 277 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 288 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 283 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 279 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 2 "C:\inetpub\wwwroot\LearnSite\student\getnotices.aspx"
    using System.Data.SqlClient;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class student_getnotices_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        
        #line 4 "C:\inetpub\wwwroot\LearnSite\student\getnotices.aspx"
                       
    protected void Page_Load(object sender, EventArgs e)
    {
        string json = "{\"notices\":[]}";

        try
        {
            int stuGrade = 0, stuClass = 0;
            try { ReadStudentInfo(out stuGrade, out stuClass); } catch { }

            string cs = GetConnStr();
            if (!string.IsNullOrEmpty(cs))
            {
                try { json = QueryNotices(cs, stuGrade, stuClass); } catch { }
            }
        }
        catch { }

        try
        {
            Response.Clear();
            Response.ContentType = "application/json; charset=utf-8";
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.Cache.SetNoStore();
            Response.AddHeader("Cache-Control", "no-cache, no-store, must-revalidate");
            Response.Write(json);
            Response.Flush();
            Response.SuppressContent = true;
            HttpContext.Current.ApplicationInstance.CompleteRequest();
        }
        catch (System.Threading.ThreadAbortException) { throw; }
        catch { }
    }

    private void ReadStudentInfo(out int grade, out int cls)
    {
        grade = 0; cls = 0;
        try
        {
            HttpCookie sc = Request.Cookies[LearnSite.Common.CookieHelp.stuCookieNname];
            if (sc == null || string.IsNullOrEmpty(sc.Value)) return;
            string val = sc.Value;
            if (val.Contains("%")) { try { val = HttpUtility.UrlDecode(val, System.Text.Encoding.UTF8); } catch { } }
            Type ct = typeof(LearnSite.Common.CookieHelp).Assembly.GetType("LearnSite.Model.Cook");
            if (ct == null) return;
            object m = Activator.CreateInstance(ct);
            System.Reflection.BindingFlags flags = System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic
                | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Static;
            System.Reflection.MethodInfo mi = ct.GetMethod("ToModel", flags);
            if (mi != null) mi.Invoke(m, new object[] { val });
            System.Reflection.PropertyInfo pg = ct.GetProperty("Sgrade");
            if (pg != null) { object v = pg.GetValue(m, null); if (v != null) int.TryParse(v.ToString(), out grade); }
            System.Reflection.PropertyInfo pc = ct.GetProperty("Sclass");
            if (pc != null) { object v = pc.GetValue(m, null); if (v != null) int.TryParse(v.ToString(), out cls); }
        }
        catch { }
    }

    private string QueryNotices(string cs, int grade, int cls)
    {
        System.Text.StringBuilder sb = new System.Text.StringBuilder();
        sb.Append("{\"notices\":[");

        using (SqlConnection conn = new SqlConnection(cs))
        {
            conn.Open();
            using (SqlCommand chk = new SqlCommand("SELECT COUNT(*) FROM sysobjects WHERE name='Notice' AND xtype='U'", conn))
            {
                if (Convert.ToInt32(chk.ExecuteScalar()) == 0)
                    return "{\"notices\":[]}";
            }
            string sql = @"SELECT TOP 20 Nid, Ntitle, Ncontent, Nhname, Ndate 
                FROM Notice WHERE Nstatus=1 
                AND (Ngrade=0 OR Ngrade=@grade) 
                AND (Nclass=0 OR Nclass=@class) 
                ORDER BY Ndate DESC";
            using (SqlCommand cmd = new SqlCommand(sql, conn))
            {
                cmd.Parameters.AddWithValue("@grade", grade);
                cmd.Parameters.AddWithValue("@class", cls);
                bool first = true;
                using (SqlDataReader dr = cmd.ExecuteReader())
                {
                    while (dr.Read())
                    {
                        if (!first) sb.Append(",");
                        first = false;
                        sb.Append("{\"nid\":").Append(dr.GetInt32(0));
                        sb.Append(",\"title\":").Append(EscJson(dr.IsDBNull(1) ? "" : dr.GetString(1)));
                        string content = "";
                        if (!dr.IsDBNull(2)) { try { content = dr.GetString(2); } catch { try { content = dr.GetValue(2).ToString(); } catch { } } }
                        sb.Append(",\"content\":").Append(EscJson(content));
                        sb.Append(",\"author\":").Append(EscJson(dr.IsDBNull(3) ? "" : dr.GetString(3)));
                        string dateStr = "";
                        if (!dr.IsDBNull(4)) { try { dateStr = dr.GetDateTime(4).ToString("yyyy-MM-dd HH:mm"); } catch { } }
                        sb.Append(",\"date\":").Append(EscJson(dateStr));
                        sb.Append("}");
                    }
                }
            }
        }
        sb.Append("]}");
        return sb.ToString();
    }

    private string EscJson(string s)
    {
        if (string.IsNullOrEmpty(s)) return "\"\"";
        System.Text.StringBuilder sb = new System.Text.StringBuilder(s.Length + 2);
        sb.Append('"');
        for (int i = 0; i < s.Length; i++)
        {
            char c = s[i];
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                case '\b': sb.Append("\\b"); break;
                case '\f': sb.Append("\\f"); break;
                default:
                    if (c < ' ') sb.AppendFormat("\\u{0:x4}", (int)c);
                    else sb.Append(c);
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private string GetConnStr()
    {
        string cs = null;
        try
        {
            Type dbType = typeof(LearnSite.Common.CookieHelp).Assembly.GetType("LearnSite.DBUtility.DbHelperSQL");
            if (dbType != null)
            {
                System.Reflection.FieldInfo f = dbType.GetField("connectionString",
                    System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
                if (f != null) cs = f.GetValue(null) as string;
            }
        }
        catch { }
        if (string.IsNullOrEmpty(cs))
        { try { cs = System.Configuration.ConfigurationManager.ConnectionStrings["SqlServer"].ConnectionString; } catch { } }
        if (cs != null && cs.ToLower().IndexOf("connection timeout") < 0 && cs.ToLower().IndexOf("connect timeout") < 0)
            cs = cs.TrimEnd(';') + ";Connection Timeout=5;";
        return cs;
    }

        #line default
        #line hidden
        
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public student_getnotices_aspx() {
            string[] dependencies;
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/student/getnotices.aspx";
            if ((global::ASP.student_getnotices_aspx.@__initialized == false)) {
                dependencies = new string[1];
                dependencies[0] = "~/student/getnotices.aspx";
                global::ASP.student_getnotices_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.student_getnotices_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(student_getnotices_aspx @__ctrl) {
            
            #line 1 "C:\inetpub\wwwroot\LearnSite\student\getnotices.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.student_getnotices_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 5381;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
