#pragma checksum "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "89252E136E0C9022FCC53EE6A8196BCB"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9066
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 284 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 281 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 283 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 279 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 285 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 276 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 278 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 275 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 1 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 282 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 286 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 277 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 280 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 289 "C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class teacher_htmledit_aspx : global::teacher_htmledit, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public teacher_htmledit_aspx() {
            string[] dependencies;
            ((global::teacher_htmledit)(this)).AppRelativeVirtualPath = "~/teacher/htmledit.aspx";
            if ((global::ASP.teacher_htmledit_aspx.@__initialized == false)) {
                global::ASP.teacher_htmledit_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[2];
                dependencies[0] = "~/teacher/htmledit.aspx";
                dependencies[1] = "~/teacher/Teach.master";
                global::ASP.teacher_htmledit_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.teacher_htmledit_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTexttitle() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 95 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.Texttitle = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "TextBoxNormal";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 95 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.ID = "Texttitle";
            
            #line default
            #line hidden
            
            #line 95 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(220, System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 95 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.CssClass = "he-input";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlCheckPublish() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 99 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.CheckPublish = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 99 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.ID = "CheckPublish";
            
            #line default
            #line hidden
            
            #line 99 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Text = "";
            
            #line default
            #line hidden
            
            #line 99 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Checked = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 106 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 106 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Text = "index.html";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control4() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 107 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 107 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Text = "w1.html";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control5() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 108 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 108 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Text = "w2.html";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control6() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 109 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 109 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Text = "w3.html";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control7() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 110 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 110 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Text = "w4.html";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control8() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 111 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 111 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Text = "w5.html";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control2(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl4 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl5;
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl5 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl6;
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl6 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDDLfilename() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.DDLfilename = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.ID = "DDLfilename";
            
            #line default
            #line hidden
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.CssClass = "he-select";
            
            #line default
            #line hidden
            
            #line 105 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            this.@__BuildControl__control2(@__ctrl.Items);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlmcontent() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            
            #line 142 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            
            #line default
            #line hidden
            this.mcontent = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 142 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.ID = "mcontent";
            
            #line default
            #line hidden
            
            #line 142 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "width: 100%; height: 450px;");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabelmsg() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 149 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Labelmsg = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 149 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.ID = "Labelmsg";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDDLMgid() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 153 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.DDLMgid = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 153 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.ID = "DDLMgid";
            
            #line default
            #line hidden
            
            #line 153 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.CssClass = "he-select";
            
            #line default
            #line hidden
            
            #line 153 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Font.Size = new System.Web.UI.WebControls.FontUnit(new System.Web.UI.WebControls.Unit(9, System.Web.UI.WebControls.UnitType.Point));
            
            #line default
            #line hidden
            
            #line 153 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(160, System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 153 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Font.Names = new string[] {
                    "Arial"};
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnedit() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 155 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.Btnedit = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "BtnNormal";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 155 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.ID = "Btnedit";
            
            #line default
            #line hidden
            
            #line 155 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Text = "修改主题";
            
            #line default
            #line hidden
            
            #line 155 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.CssClass = "he-btn he-btn-primary";
            
            #line default
            #line hidden
            
            #line 155 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Click -= new System.EventHandler(this.Btnedit_Click);
            
            #line default
            #line hidden
            
            #line 155 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Click += new System.EventHandler(this.Btnedit_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnCourse() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 156 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.BtnCourse = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "BtnNormal";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 156 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.ID = "BtnCourse";
            
            #line default
            #line hidden
            
            #line 156 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Text = "学案返回";
            
            #line default
            #line hidden
            
            #line 156 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.CssClass = "he-btn he-btn-secondary";
            
            #line default
            #line hidden
            
            #line 156 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Click -= new System.EventHandler(this.BtnCourse_Click);
            
            #line default
            #line hidden
            
            #line 156 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Click += new System.EventHandler(this.BtnCourse_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl1 = this.@__BuildControlTexttitle();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl2;
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl2 = this.@__BuildControlCheckPublish();
            
            #line default
            #line hidden
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl3;
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl3 = this.@__BuildControlDDLfilename();
            
            #line default
            #line hidden
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl4;
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl4 = this.@__BuildControlmcontent();
            
            #line default
            #line hidden
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl5;
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl5 = this.@__BuildControlLabelmsg();
            
            #line default
            #line hidden
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl6;
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl6 = this.@__BuildControlDDLMgid();
            
            #line default
            #line hidden
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl7;
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl7 = this.@__BuildControlBtnedit();
            
            #line default
            #line hidden
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl8;
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl8 = this.@__BuildControlBtnCourse();
            
            #line default
            #line hidden
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderContent1));
        }
        
        private void @__RenderContent1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.WriteUTF8ResourceString(@__w, 212736, 4352, false);
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n            <div class=\"he-divider\"></div>\r\n            <di" +
                    "v class=\"he-check-wrap\">\r\n                ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n                <label for=\"");
            
            #line 100 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
                    @__w.Write( CheckPublish.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\">是否发布</label>\r\n            </div>\r\n            <div class=\"he-divider\"></div>\r\n " +
                    "           <div class=\"he-field\">\r\n                <span class=\"he-label\">网页文件名<" +
                    "/span>\r\n                ");
            parameterContainer.Controls[2].RenderControl(@__w);
            this.WriteUTF8ResourceString(@__w, 217088, 386, true);
            
            #line 124 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
                  @__w.Write(myCid() );

            
            #line default
            #line hidden
            this.WriteUTF8ResourceString(@__w, 217474, 853, true);
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n        </div>\r\n    </div>\r\n\r\n    <!-- Actions Card -->\r\n    <div class=\"he-car" +
                    "d\">\r\n        <div class=\"he-actions\">\r\n            <div class=\"he-msg\">");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write("</div>\r\n            <div class=\"he-actions-right\">\r\n                <div class=\"h" +
                    "e-field\">\r\n                    <span class=\"he-label\">自定义评价标准</span>\r\n          " +
                    "          ");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write("\r\n                </div>\r\n                ");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write("\r\n                ");
            parameterContainer.Controls[7].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n</div>\r\n");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(teacher_htmledit_aspx @__ctrl) {
            
            #line 1 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__ctrl.MasterPageFile = "~/teacher/Teach.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            this.AddContentTemplate("Content", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\inetpub\wwwroot\LearnSite\teacher\htmledit.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.teacher_htmledit_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.teacher_htmledit_aspx.@__fileDependencies);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -622218518;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
